/* ===== 计算机网络 + 联通企业文化题库 ===== */
window.NET_QUESTIONS = [
  { id: 'NET_001', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'OSI 参考模型共分为几层？',
    options: ['A. 7层', 'B. 5层', 'C. 4层', 'D. 3层'],
    answer: 'A', tags: ['OSI'],
    analysis: 'OSI 七层：物理层、数据链路层、网络层、传输层、会话层、表示层、应用层。TCP/IP 为四/五层。' },

  { id: 'NET_002', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'OSI 模型中，负责端到端可靠传输的是哪一层？',
    options: ['A. 传输层', 'B. 网络层', 'C. 数据链路层', 'D. 物理层'],
    answer: 'A', tags: ['OSI', '传输层'],
    analysis: '传输层（TCP/UDP）负责端到端通信；网络层（IP）负责路由寻址。' },

  { id: 'NET_003', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'IP 地址属于 OSI 模型的哪一层？',
    options: ['A. 网络层', 'B. 传输层', 'C. 应用层', 'D. 数据链路层'],
    answer: 'A', tags: ['OSI', '网络层'],
    analysis: 'IP 是网络层协议；TCP/UDP 是传输层；HTTP/DNS 是应用层。' },

  { id: 'NET_004', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'TCP 三次握手建立连接，正确的顺序是？',
    options: ['A. SYN → SYN+ACK → ACK', 'B. SYN → ACK → SYN', 'C. ACK → SYN → SYN+ACK', 'D. SYN+ACK → SYN → ACK'],
    answer: 'A', tags: ['TCP', '三次握手'],
    analysis: '客户端发 SYN → 服务器回 SYN+ACK → 客户端发 ACK，共三次。' },

  { id: 'NET_005', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'TCP 断开连接需要几次挥手？',
    options: ['A. 四次', 'B. 三次', 'C. 两次', 'D. 五次'],
    answer: 'A', tags: ['TCP', '四次挥手'],
    analysis: 'TCP 全双工，断开需四次挥手（FIN→ACK→FIN→ACK）。' },

  { id: 'NET_006', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'TCP 与 UDP 的区别，正确的是？',
    options: ['A. TCP 面向连接可靠，UDP 无连接不可靠', 'B. TCP 无连接，UDP 面向连接', 'C. 都可靠', 'D. 都不可靠'],
    answer: 'A', tags: ['TCP', 'UDP'],
    analysis: 'TCP 面向连接、可靠（重传/校验）、有流量控制；UDP 无连接、快、不可靠，用于实时音视频/DNS 等。' },

  { id: 'NET_007', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'HTTP 默认端口是？',
    options: ['A. 80', 'B. 443', 'C. 22', 'D. 21'],
    answer: 'A', tags: ['端口', 'HTTP'],
    analysis: 'HTTP=80，HTTPS=443，SSH=22，FTP=21，DNS=53。' },

  { id: 'NET_008', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'HTTPS 使用的默认端口是？',
    options: ['A. 443', 'B. 80', 'C. 8080', 'D. 3306'],
    answer: 'A', tags: ['端口', 'HTTPS'],
    analysis: 'HTTPS=443（SSL/TLS 加密的 HTTP）；MySQL=3306。' },

  { id: 'NET_009', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'DNS 的作用是？',
    options: ['A. 把域名解析为 IP 地址', 'B. 分配 IP 地址', 'C. 加密传输', 'D. 路由选择'],
    answer: 'A', tags: ['DNS'],
    analysis: 'DNS（域名系统）把域名（如 baidu.com）解析成 IP；DHCP 才分配 IP。' },

  { id: 'NET_010', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'IP 地址 192.168.1.1 属于哪类地址？',
    options: ['A. C类（私网）', 'B. A类', 'C. B类', 'D. D类'],
    answer: 'A', tags: ['IP地址'],
    analysis: '192 开头为 C 类；私网段：10.x(A)、172.16-31.x(B)、192.168.x(C)。' },

  { id: 'NET_011', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: '子网掩码 255.255.255.0 对应的网络位数是？',
    options: ['A. 24位', 'B. 16位', 'C. 8位', 'D. 32位'],
    answer: 'A', tags: ['子网掩码'],
    analysis: '255.255.255.0 = 前 24 位为网络位（/24），后 8 位为主机位。' },

  { id: 'NET_012', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'ping 命令使用的协议是？',
    options: ['A. ICMP', 'B. TCP', 'C. UDP', 'D. ARP'],
    answer: 'A', tags: ['ICMP'],
    analysis: 'ping 使用 ICMP（网络层控制报文协议）探测连通性。' },

  { id: 'NET_013', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'HTTP 与 HTTPS 的主要区别是？',
    options: ['A. HTTPS 增加了 SSL/TLS 加密', 'B. HTTPS 更快', 'C. HTTP 更安全', 'D. 没有区别'],
    answer: 'A', tags: ['HTTP', 'HTTPS'],
    analysis: 'HTTPS = HTTP + SSL/TLS 加密，端口 443，防窃听篡改。' },

  { id: 'NET_014', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: 'HTTP 状态码 404 表示？',
    options: ['A. 请求的资源不存在', 'B. 服务器内部错误', 'C. 请求成功', 'D. 未授权'],
    answer: 'A', tags: ['HTTP状态码'],
    analysis: '404=未找到；200=成功；500=服务器内部错误；401/403=未授权/禁止。' },

  { id: 'NET_015', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'HTTP 状态码 500 表示？',
    options: ['A. 服务器内部错误', 'B. 资源不存在', 'C. 请求成功', 'D. 重定向'],
    answer: 'A', tags: ['HTTP状态码'],
    analysis: '500=服务器内部错误；3xx=重定向；4xx=客户端错误。' },

  { id: 'NET_016', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: '下列哪个是 TCP 协议的特点？',
    options: ['A. 可靠、面向连接、有拥塞控制', 'B. 不可靠、无连接', 'C. 用于实时视频直播', 'D. 无需握手'],
    answer: 'A', tags: ['TCP'],
    analysis: 'TCP 可靠面向连接，有重传、流量/拥塞控制；UDP 快但不可靠，适合直播/游戏。' },

  { id: 'NET_017', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'ARP 协议的作用是？',
    options: ['A. 把 IP 地址解析为 MAC 地址', 'B. 把域名解析为 IP', 'C. 分配 IP 地址', 'D. 加密数据'],
    answer: 'A', tags: ['ARP'],
    analysis: 'ARP 在同一局域网内把 IP 映射为物理 MAC 地址；DNS 域名→IP；DHCP 分配 IP。' },

  { id: 'NET_018', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'DHCP 协议的作用是？',
    options: ['A. 自动分配 IP 地址', 'B. 解析域名', 'C. 加密传输', 'D. 建立连接'],
    answer: 'A', tags: ['DHCP'],
    analysis: 'DHCP 自动给主机分配 IP、子网掩码、网关、DNS。' },

  { id: 'NET_019', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'TCP 三次握手中，第二次握手发送的报文是？',
    options: ['A. SYN + ACK', 'B. SYN', 'C. ACK', 'D. FIN'],
    answer: 'A', tags: ['TCP', '三次握手'],
    analysis: '第一次客户端 SYN，第二次服务器 SYN+ACK，第三次客户端 ACK。' },

  { id: 'NET_020', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: '关于 TCP 和 UDP 的应用场景，正确的是？',
    options: ['A. 文件传输/邮件用 TCP，直播/游戏用 UDP', 'B. 直播用 TCP', 'C. 邮件用 UDP', 'D. 文件传输用 UDP'],
    answer: 'A', tags: ['TCP', 'UDP'],
    analysis: '需要可靠的用 TCP（HTTP/FTP/邮件/文件）；实时性优先容忍丢包的用 UDP（直播/语音/游戏/DNS）。' },

  { id: 'NET_021', module: 'net', type: 'choice', difficulty: 1, source: '小林coding',
    question: '浏览器输入网址后，首先进行的操作是？',
    options: ['A. DNS 解析域名', 'B. 直接发 HTTP 请求', 'C. 建立 TCP 连接', 'D. 渲染页面'],
    answer: 'A', tags: ['网页访问流程'],
    analysis: '流程：DNS 解析 → TCP 握手 → 发 HTTP 请求 → 服务器响应 → 渲染页面。' },

  { id: 'NET_022', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'TCP 滑动窗口机制的作用是？',
    options: ['A. 流量控制', 'B. 域名解析', 'C. IP 路由', 'D. 数据加密'],
    answer: 'A', tags: ['TCP', '流量控制'],
    analysis: '滑动窗口用于流量控制，让接收方告知发送方还能接收多少数据，避免溢出。' },

  { id: 'NET_023', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: '私网 IP 地址段不包括下列哪个？',
    options: ['A. 192.169.1.x', 'B. 10.0.0.0/8', 'C. 172.16.0.0/12', 'D. 192.168.0.0/16'],
    answer: 'A', tags: ['IP地址'],
    analysis: '私网段：10.0.0.0/8、172.16.0.0/12、192.168.0.0/16。192.169.x 是公网地址。' },

  { id: 'NET_024', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: 'FTP 协议默认使用哪个端口传输数据（控制端口）？',
    options: ['A. 21', 'B. 80', 'C. 22', 'D. 25'],
    answer: 'A', tags: ['端口', 'FTP'],
    analysis: 'FTP 控制端口 21；SSH=22；SMTP 邮件=25；HTTP=80。' },

  { id: 'NET_025', module: 'net', type: 'choice', difficulty: 2, source: '小林coding',
    question: '关于 HTTP 的 GET 和 POST，正确的是？',
    options: ['A. GET 参数在 URL 中，POST 参数在请求体中', 'B. GET 参数在请求体', 'C. POST 参数在 URL', 'D. 完全相同'],
    answer: 'A', tags: ['HTTP方法'],
    analysis: 'GET 参数拼在 URL（有长度限制、会缓存），POST 放请求体（更安全、可传大数据）。' }
];

window.UNICOM_QUESTIONS = [
  { id: 'UC_001', module: 'unicom', type: 'choice', difficulty: 1, source: '联通官网',
    question: '中国联通的英文简称是？',
    options: ['A. China Unicom', 'B. China Telecom', 'C. China Mobile', 'D. China Netcom'],
    answer: 'A', tags: ['企业文化'],
    analysis: '中国联通 = China Unicom；电信 = China Telecom；移动 = China Mobile。' },

  { id: 'UC_002', module: 'unicom', type: 'choice', difficulty: 1, source: '联通官网',
    question: '我国三大电信运营商是？',
    options: ['A. 中国联通、中国移动、中国电信', 'B. 中国联通、中国移动、中国铁通', 'C. 中国电信、中国移动、中国网通', 'D. 中国联通、中国网通、中国铁通'],
    answer: 'A', tags: ['企业文化'],
    analysis: '三大运营商：中国移动、中国电信、中国联通（2008年网通并入联通）。' },

  { id: 'UC_003', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '中国联通在 2026 年《财富》世界 500 强中的排名是？',
    options: ['A. 第281位', 'B. 第181位', 'C. 第381位', 'D. 前100位'],
    answer: 'A', tags: ['企业文化'],
    analysis: '根据学习计划，联通 2026 年世界 500 强排名第 281 位（需以当年最新榜单为准）。' },

  { id: 'UC_004', module: 'unicom', type: 'choice', difficulty: 1, source: '联通官网',
    question: '以下哪个不是中国联通的核心业务？',
    options: ['A. 芯片制造', 'B. 5G', 'C. 千兆宽带', 'D. 联通云'],
    answer: 'A', tags: ['业务'],
    analysis: '联通核心业务：5G、千兆宽带、联通云、大数据、物联网、AI 等，不含芯片制造。' },

  { id: 'UC_005', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '中国联通提出的品牌口号/定位（近年的"新定位"）更接近？',
    options: ['A. 数字信息基础设施运营服务国家队、网络强国主力军', 'B. 全球最大芯片制造商', 'C. 电商平台', 'D. 社交网络'],
    answer: 'A', tags: ['企业文化'],
    analysis: '联通定位为"数字信息基础设施运营服务国家队、网络强国数字中国智慧社会建设主力军"。' },

  { id: 'UC_006', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '中国联通的 5G 品牌名称是？',
    options: ['A. 联通沃5G / 联通智家', 'B. 移动5G', 'C. 天翼5G', 'D. 铁通5G'],
    answer: 'A', tags: ['5G'],
    analysis: '联通 5G 相关品牌常称"联通沃"系列（沃5G），家庭业务"联通智家"。' },

  { id: 'UC_007', module: 'unicom', type: 'choice', difficulty: 1, source: '联通官网',
    question: '中国联通总部所在地是？',
    options: ['A. 北京', 'B. 上海', 'C. 深圳', 'D. 天津'],
    answer: 'A', tags: ['企业文化'],
    analysis: '中国联通总部设在北京。' },

  { id: 'UC_008', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '中国联通的物联网业务品牌常称为？',
    options: ['A. 联通物联网 / 雁飞', 'B. 天翼物联', 'C. OneNET', 'D. 移动物联'],
    answer: 'A', tags: ['物联网'],
    analysis: '联通物联网平台（雁飞系列）；天翼物联是电信；OneNET 是中国移动的物联网平台。' },

  { id: 'UC_009', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '"联通云"是中国联通提供的哪类服务？',
    options: ['A. 云计算服务', 'B. 社交平台', 'C. 电商', 'D. 短视频'],
    answer: 'A', tags: ['联通云'],
    analysis: '联通云是联通的云计算与算力服务品牌。' },

  { id: 'UC_010', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '中国联通经营牌照的移动通信制式，5G 主要采用？',
    options: ['A. 5G NR（新空口）', 'B. GSM', 'C. CDMA', 'D. 3G WCDMA'],
    answer: 'A', tags: ['5G'],
    analysis: '5G 采用 5G NR 标准；联通历史上用 GSM/WCDMA 演进，电信用 CDMA。' },

  { id: 'UC_011', module: 'unicom', type: 'choice', difficulty: 1, source: '联通官网',
    question: '三大运营商中，负责北方固网/宽带历史基础的是（网通并入后）？',
    options: ['A. 中国联通', 'B. 中国移动', 'C. 中国电信', 'D. 中国铁通'],
    answer: 'A', tags: ['企业文化'],
    analysis: '2008 年中国网通并入中国联通，联通在北方固网/宽带基础较强；电信南方较强。' },

  { id: 'UC_012', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '联通"千兆宽带"指的是？',
    options: ['A. 宽带速率达千兆（1000Mbps）', 'B. 价格千元', 'C. 覆盖千户', 'D. 延迟千毫秒'],
    answer: 'A', tags: ['业务'],
    analysis: '千兆宽带 = 下行速率 1000Mbps 的家用光纤宽带。' },

  { id: 'UC_013', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '联通在大数据领域的业务方向，下列说法正确的是？',
    options: ['A. 大数据平台与数据治理、行业解决方案', 'B. 只做硬件', 'C. 不做数据业务', 'D. 只卖手机'],
    answer: 'A', tags: ['大数据'],
    analysis: '联通提供大数据平台、数据治理及政企行业数字化解决方案。' },

  { id: 'UC_014', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '以下关于"智慧城市/数字政府"的说法，与联通业务相符的是？',
    options: ['A. 联通提供数字政府、智慧城市整体解决方案', 'B. 与运营商无关', 'C. 只做个人手机', 'D. 仅做游戏'],
    answer: 'A', tags: ['智慧城市'],
    analysis: '联通深耕数字政府、智慧城市、工业互联网等政企业务。' },

  { id: 'UC_015', module: 'unicom', type: 'choice', difficulty: 2, source: '联通官网',
    question: '联通推出的面向个人/家庭的智能连接产品组合常被称为？',
    options: ['A. 联通智家', 'B. 联通商城', 'C. 联通音乐', 'D. 联通游戏'],
    answer: 'A', tags: ['业务'],
    analysis: '联通智家是面向家庭的智能宽带与智慧生活产品品牌。' }
];
