/* ===== SQL题库：45道选择题（对齐牛客网SQL篇 / 大厂笔试真题） ===== */
window.SQL_QUESTIONS = [
  { id: 'SQL_001', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '以下哪个 SQL 语句用于从表中查询所有列？',
    options: ['A. SELECT * FROM 表名;', 'B. SELECT ALL FROM 表名;', 'C. GET * FROM 表名;', 'D. QUERY * FROM 表名;'],
    answer: 'A', tags: ['SELECT', '基础'],
    analysis: 'SELECT * 表示选择所有列，FROM 指定表名。B/C/D 都不是标准 SQL 语法。' },

  { id: 'SQL_002', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '查询结果想去掉重复行，应使用哪个关键字？',
    options: ['A. UNIQUE', 'B. DISTINCT', 'C. DIFFERENT', 'D. DUPLICATE'],
    answer: 'B', tags: ['SELECT', '去重'],
    analysis: 'SELECT DISTINCT 列名 用于去除重复记录。UNIQUE 是约束（唯一约束），不是查询关键字。' },

  { id: 'SQL_003', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'WHERE 子句中的 = NULL 能否正确筛选出值为 NULL 的记录？',
    options: ['A. 能', 'B. 不能，应用 IS NULL', 'C. 只有 MySQL 能', 'D. 取决于数据类型'],
    answer: 'B', tags: ['WHERE', 'NULL'],
    analysis: 'NULL 表示未知值，= NULL 结果恒为未知（不成立），必须用 IS NULL / IS NOT NULL 判断。' },

  { id: 'SQL_004', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '对结果按某列升序排序，应使用哪个子句？',
    options: ['A. GROUP BY 列名', 'B. SORT BY 列名 ASC', 'C. ORDER BY 列名 ASC', 'D. ORDER 列名 ASC'],
    answer: 'C', tags: ['ORDER BY'],
    analysis: 'ORDER BY 用于排序，ASC 升序（默认）、DESC 降序。标准 SQL 没有 SORT BY。' },

  { id: 'SQL_005', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '统计某列非空记录数量的聚合函数是？',
    options: ['A. COUNT(*)', 'B. COUNT(列名)', 'C. SUM(列名)', 'D. MAX(列名)'],
    answer: 'B', tags: ['聚合函数'],
    analysis: 'COUNT(列名) 统计该列非 NULL 的行数；COUNT(*) 统计所有行（含 NULL）。SUM 求和，MAX 求最大值。' },

  { id: 'SQL_006', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'SELECT AVG(score) FROM student; 的作用是？',
    options: ['A. 求 score 总和', 'B. 求 score 平均值', 'C. 求 score 最大值', 'D. 统计 score 行数'],
    answer: 'B', tags: ['聚合函数'],
    analysis: 'AVG 求平均值，SUM 求和，MAX/MIN 求最大/最小，COUNT 统计数量。' },

  { id: 'SQL_007', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'HAVING 子句的作用是？',
    options: ['A. 对分组后的结果进行过滤', 'B. 对原始记录进行过滤', 'C. 对结果排序', 'D. 去除重复行'],
    answer: 'A', tags: ['GROUP BY', 'HAVING'],
    analysis: 'WHERE 在分组前过滤原始行，HAVING 在 GROUP BY 分组后对聚合结果过滤。' },

  { id: 'SQL_008', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'WHERE 与 HAVING 的主要区别是？',
    options: ['A. WHERE 对分组前数据过滤，HAVING 对分组后数据过滤', 'B. 完全相同', 'C. HAVING 用于排序', 'D. WHERE 只能用于聚合函数'],
    answer: 'A', tags: ['WHERE', 'HAVING'],
    analysis: 'WHERE 作用于原始行（不能使用聚合函数），HAVING 作用于分组聚合后的结果（常用聚合函数）。' },

  { id: 'SQL_009', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '内连接（INNER JOIN）返回的是？',
    options: ['A. 两个表中满足连接条件的行', 'B. 左表全部行', 'C. 右表全部行', 'D. 两表全部行'],
    answer: 'A', tags: ['JOIN'],
    analysis: 'INNER JOIN 只返回两表匹配上的行。LEFT/RIGHT JOIN 保留一侧全部行，FULL JOIN 保留两侧全部。' },

  { id: 'SQL_010', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'LEFT JOIN 中，左表有但右表无匹配的记录，右表字段显示为？',
    options: ['A. NULL', 'B. 0', 'C. 空字符串', 'D. 报错'],
    answer: 'A', tags: ['JOIN', 'NULL'],
    analysis: 'LEFT JOIN 保留左表所有行，右表无匹配时对应字段为 NULL。' },

  { id: 'SQL_011', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '查询成绩在 60 到 90 分之间的记录，正确的是？',
    options: ['A. WHERE score BETWEEN 60 AND 90', 'B. WHERE 60 <= score <= 90', 'C. WHERE score IN (60, 90)', 'D. WHERE score > 60 AND < 90'],
    answer: 'A', tags: ['WHERE', 'BETWEEN'],
    analysis: 'BETWEEN ... AND ... 是闭区间（含边界）。B 语法错误，C 是离散值，D 语法错误。' },

  { id: 'SQL_012', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '模糊查询姓名中包含"张"字，应使用？',
    options: ['A. WHERE name LIKE "%张%"', 'B. WHERE name = "张"', 'C. WHERE name LIKE "张"', 'D. WHERE name CONTAINS "张"'],
    answer: 'A', tags: ['LIKE'],
    analysis: 'LIKE 做模糊匹配，% 表示任意多个字符，_ 表示任意单个字符。B/C 是精确匹配，D 不是标准语法。' },

  { id: 'SQL_013', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '向表中插入一条记录，使用哪个语句？',
    options: ['A. ADD', 'B. INSERT INTO', 'C. PUT', 'D. CREATE'],
    answer: 'B', tags: ['DML', 'INSERT'],
    analysis: 'INSERT INTO 表名 (列...) VALUES (值...) 用于插入数据。ADD 是修改表结构加列，CREATE 建表。' },

  { id: 'SQL_014', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '修改表中已有记录，使用哪个语句？',
    options: ['A. CHANGE', 'B. ALTER', 'C. UPDATE', 'D. MODIFY'],
    answer: 'C', tags: ['DML', 'UPDATE'],
    analysis: 'UPDATE 表名 SET 列=值 WHERE 条件 用于修改数据。ALTER 修改表结构，不是数据。' },

  { id: 'SQL_015', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '删除表中所有记录但保留表结构，使用？',
    options: ['A. DROP TABLE', 'B. DELETE FROM 表名', 'C. TRUNCATE TABLE 表名', 'D. B 和 C 都可以'],
    answer: 'D', tags: ['DML', 'DDL'],
    analysis: 'DELETE 和 TRUNCATE 都能清空数据保留表结构；DROP 会删除整个表。TRUNCATE 更快且不可回滚。' },

  { id: 'SQL_016', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '事务的四大特性（ACID）不包括以下哪个？',
    options: ['A. 原子性 Atomicity', 'B. 一致性 Consistency', 'C. 隔离性 Isolation', 'D. 可靠性 Durability 之外的"可用性"'],
    answer: 'D', tags: ['事务'],
    analysis: 'ACID = 原子性(A)、一致性(C)、隔离性(I)、持久性(D=Durability 持久性)。没有"可用性(Availability)"。' },

  { id: 'SQL_017', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '主键（PRIMARY KEY）的特性，错误的是？',
    options: ['A. 唯一', 'B. 非空', 'C. 一个表可有多个主键', 'D. 可被外键引用'],
    answer: 'C', tags: ['约束', '主键'],
    analysis: '主键唯一且非空，一个表只能有一个主键（但可由多列组成联合主键）。C 错误。' },

  { id: 'SQL_018', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '外键（FOREIGN KEY）的作用是？',
    options: ['A. 保证引用完整性', 'B. 加快查询速度', 'C. 自动排序', 'D. 保证唯一性'],
    answer: 'A', tags: ['约束', '外键'],
    analysis: '外键约束子表某列引用父表主键，保证数据引用完整性。加速查询靠索引，唯一性靠 UNIQUE。' },

  { id: 'SQL_019', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '唯一约束与主键的区别，正确的是？',
    options: ['A. 主键非空且唯一，唯一约束允许 NULL', 'B. 两者完全相同', 'C. 唯一约束必须非空', 'D. 主键允许 NULL'],
    answer: 'A', tags: ['约束'],
    analysis: '主键非空+唯一（一个表一个）；UNIQUE 唯一但允许多个 NULL（一个表可有多个唯一约束）。' },

  { id: 'SQL_020', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '索引（INDEX）的主要作用是？',
    options: ['A. 加快查询速度', 'B. 减少存储空间', 'C. 保证数据唯一', 'D. 替代主键'],
    answer: 'A', tags: ['索引'],
    analysis: '索引通过建立查找结构加速查询，但会占用额外空间并降低写入性能。' },

  { id: 'SQL_021', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '关于索引的说法，错误的是？',
    options: ['A. 索引能加速所有查询', 'B. 索引占存储空间', 'C. 索引会降低插入/更新速度', 'D. 主键默认建索引'],
    answer: 'A', tags: ['索引'],
    analysis: '索引并非加速所有查询（如小表、全表扫描、低选择性列可能更慢），还会降低写入性能、占空间。' },

  { id: 'SQL_022', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '视图（VIEW）的本质是？',
    options: ['A. 存储的查询结果（虚拟表）', 'B. 物理存储的表', 'C. 临时表', 'D. 索引'],
    answer: 'A', tags: ['视图'],
    analysis: '视图是基于查询定义的虚拟表，本身不存储数据，数据来自基表。' },

  { id: 'SQL_023', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'GROUP BY 子句的作用是？',
    options: ['A. 按某列分组，常与聚合函数配合', 'B. 排序', 'C. 去重', 'D. 连接表'],
    answer: 'A', tags: ['GROUP BY'],
    analysis: 'GROUP BY 按指定列分组，每组的聚合函数（COUNT/SUM/AVG...）分别计算。' },

  { id: 'SQL_024', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'SELECT 语句中，LIMIT 2, 5 表示？',
    options: ['A. 跳过2条取5条', 'B. 取第2到第5条', 'C. 取前2条', 'D. 取前5条'],
    answer: 'A', tags: ['LIMIT'],
    analysis: 'LIMIT 偏移量, 条数。LIMIT 2,5 表示从第3条开始取5条（跳过前2条）。' },

  { id: 'SQL_025', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '子查询（Subquery）是什么？',
    options: ['A. 嵌套在另一个查询中的查询', 'B. 独立的多表查询', 'C. 存储过程', 'D. 视图'],
    answer: 'A', tags: ['子查询'],
    analysis: '子查询是嵌套在 SELECT/WHERE/FROM 中的查询，常用于 IN、EXISTS、比较等场景。' },

  { id: 'SQL_026', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下聚合函数中，可作用于任意数据类型的是？',
    options: ['A. COUNT', 'B. SUM', 'C. AVG', 'D. MAX'],
    answer: 'A', tags: ['聚合函数'],
    analysis: 'COUNT 统计数量可用于任意类型；SUM/AVG 需数值；MAX/MIN 需可比较类型。' },

  { id: 'SQL_027', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: '创建表的语句是？',
    options: ['A. CREATE TABLE', 'B. NEW TABLE', 'C. MAKE TABLE', 'D. ADD TABLE'],
    answer: 'A', tags: ['DDL'],
    analysis: 'CREATE TABLE 表名 (列定义...) 用于建表。' },

  { id: 'SQL_028', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '查询学生表中每个班级的人数，正确的语句是？',
    options: ['A. SELECT class, COUNT(*) FROM student GROUP BY class', 'B. SELECT class, COUNT(*) FROM student', 'C. SELECT class FROM student GROUP BY class', 'D. SELECT COUNT(class) FROM student GROUP BY class'],
    answer: 'A', tags: ['GROUP BY'],
    analysis: '按 class 分组统计人数，需 GROUP BY class 并 SELECT class 和 COUNT(*)。B 无分组，D 缺 class 列。' },

  { id: 'SQL_029', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'COUNT(*) 与 COUNT(某列) 的区别是？',
    options: ['A. COUNT(*) 统计所有行，COUNT(列) 统计该列非空行', 'B. 完全相同', 'C. COUNT(*) 只统计非空', 'D. COUNT(列) 统计所有行'],
    answer: 'A', tags: ['聚合函数'],
    analysis: 'COUNT(*) 统计总行数（含 NULL），COUNT(列) 只统计该列非 NULL 的行。' },

  { id: 'SQL_030', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '关于 DELETE 和 TRUNCATE 的说法，错误的是？',
    options: ['A. TRUNCATE 可以带 WHERE 条件', 'B. DELETE 可带 WHERE 条件', 'C. TRUNCATE 速度更快', 'D. DELETE 可回滚（事务中）'],
    answer: 'A', tags: ['DML', 'DDL'],
    analysis: 'TRUNCATE 是 DDL，清空整表，不能带 WHERE；DELETE 可带 WHERE 删部分数据。' },

  { id: 'SQL_031', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'LEFT JOIN 中，ON 和 WHERE 的区别是？',
    options: ['A. ON 决定连接条件，WHERE 过滤连接后的结果', 'B. 完全相同', 'C. WHERE 决定连接条件', 'D. ON 过滤结果'],
    answer: 'A', tags: ['JOIN'],
    analysis: 'ON 指定两表连接条件；WHERE 对连接后的结果集过滤。对 LEFT JOIN，WHERE 对右表 NULL 行的过滤会影响保留行为。' },

  { id: 'SQL_032', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'GROUP BY 与 DISTINCT 都能去重，主要区别是？',
    options: ['A. GROUP BY 可配合聚合函数，DISTINCT 不能', 'B. DISTINCT 可配合聚合函数', 'C. 完全相同', 'D. GROUP BY 不能去重'],
    answer: 'A', tags: ['GROUP BY', 'DISTINCT'],
    analysis: 'DISTINCT 只去除重复行；GROUP BY 分组后每组可用聚合函数统计。' },

  { id: 'SQL_033', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'MySQL 中查看表结构的语句是？',
    options: ['A. DESC 表名', 'B. SHOW 表名', 'C. VIEW 表名', 'D. LIST 表名'],
    answer: 'A', tags: ['DDL', 'MySQL'],
    analysis: 'DESC 表名（或 DESCRIBE 表名）查看表结构。SHOW TABLES 查看所有表。' },

  { id: 'SQL_034', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '聚合函数 COUNT/SUM 等可与 NULL 一起运算时的行为，正确的是？',
    options: ['A. 聚合函数会忽略 NULL', 'B. 聚合函数会把 NULL 当 0', 'C. 会报错', 'D. 取决于数据库'],
    answer: 'A', tags: ['聚合函数', 'NULL'],
    analysis: '除 COUNT(*) 外，聚合函数（SUM/AVG/COUNT(列)/MAX/MIN）计算时忽略 NULL 值。' },

  { id: 'SQL_035', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '三级范式（3NF）的核心要求是？',
    options: ['A. 消除非主属性对主键的传递依赖', 'B. 消除部分依赖', 'C. 所有属性都不可再分', 'D. 必须有外键'],
    answer: 'A', tags: ['范式'],
    analysis: '1NF=属性原子性；2NF=消除部分依赖；3NF=消除传递依赖。' },

  { id: 'SQL_036', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'SQL 中连接多个条件的逻辑运算符，表示"且"的是？',
    options: ['A. AND', 'B. OR', 'C. NOT', 'D. XOR'],
    answer: 'A', tags: ['运算符'],
    analysis: 'AND 表示且（都满足），OR 表示或（满足其一），NOT 取反。' },

  { id: 'SQL_037', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '查询时给列起别名，正确的语法是？',
    options: ['A. SELECT 列名 AS 别名 FROM 表名', 'B. SELECT 列名 WHERE 别名', 'C. SELECT 别名 = 列名 FROM 表名', 'D. SELECT 列名 IN 别名'],
    answer: 'A', tags: ['SELECT', '别名'],
    analysis: 'AS 关键字给列或表起别名，也可省略 AS 直接写 SELECT 列名 别名。' },

  { id: 'SQL_038', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '关于 UNION 和 UNION ALL 的区别，正确的是？',
    options: ['A. UNION 去重，UNION ALL 保留重复', 'B. UNION ALL 去重', 'C. 完全相同', 'D. UNION 保留重复'],
    answer: 'A', tags: ['集合运算'],
    analysis: 'UNION 合并结果并去重（较慢），UNION ALL 直接合并不去重（较快）。' },

  { id: 'SQL_039', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '数据库事务隔离级别中，可避免脏读、不可重复读、幻读的级别是？',
    options: ['A. 可串行化 Serializable', 'B. 读已提交 Read Committed', 'C. 读未提交 Read Uncommitted', 'D. 可重复读 Repeatable Read'],
    answer: 'A', tags: ['事务', '隔离级别'],
    analysis: 'Serializable 最高级别，避免脏读/不可重复读/幻读，但并发性最低。' },

  { id: 'SQL_040', module: 'sql', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'DDL 指的是？',
    options: ['A. 数据定义语言（建表/改表/删表）', 'B. 数据操作语言（增删改）', 'C. 数据查询语言', 'D. 事务控制语言'],
    answer: 'A', tags: ['SQL分类'],
    analysis: 'DDL=数据定义（CREATE/ALTER/DROP）；DML=数据操作（INSERT/UPDATE/DELETE）；DQL=查询（SELECT）。' },

  { id: 'SQL_041', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'MySQL 中，查询前 5 条记录的标准写法是？',
    options: ['A. SELECT * FROM 表名 LIMIT 5', 'B. SELECT TOP 5 * FROM 表名', 'C. SELECT FIRST 5 * FROM 表名', 'D. SELECT * FROM 表名 WHERE ROWNUM <= 5'],
    answer: 'A', tags: ['LIMIT', 'MySQL'],
    analysis: 'MySQL 用 LIMIT 5 取前 5 条；TOP 是 SQL Server 写法；ROWNUM 是 Oracle 写法。' },

  { id: 'SQL_042', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'EXISTS 子查询返回的结果是？',
    options: ['A. 布尔值（存在与否）', 'B. 结果集', 'C. 数值', 'D. 字符串'],
    answer: 'A', tags: ['子查询', 'EXISTS'],
    analysis: 'EXISTS 判断子查询是否有返回行，返回布尔值，常用于相关子查询。' },

  { id: 'SQL_043', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '关于索引，说法正确的是？',
    options: ['A. 适合建在 WHERE/ORDER BY 频繁使用的列上', 'B. 索引越多越好', 'C. 索引不占空间', 'D. 索引加快写入'],
    answer: 'A', tags: ['索引'],
    analysis: '在查询频繁的列建索引能提速；索引过多会拖慢写入、占空间，并非越多越好。' },

  { id: 'SQL_044', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'SELECT 子句执行顺序（逻辑顺序）正确的是？',
    options: ['A. FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY', 'B. SELECT → FROM → WHERE → ORDER BY', 'C. FROM → SELECT → WHERE → HAVING', 'D. WHERE → FROM → SELECT → ORDER BY'],
    answer: 'A', tags: ['执行顺序'],
    analysis: '逻辑顺序：FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT。这也是 HAVING 能引用聚合而 WHERE 不能的原因。' },

  { id: 'SQL_045', module: 'sql', type: 'choice', difficulty: 2, source: '牛客网',
    question: '存储过程（Stored Procedure）的特点，错误的是？',
    options: ['A. 无法包含控制流语句', 'B. 可减少网络传输', 'C. 可复用', 'D. 预编译提高性能'],
    answer: 'A', tags: ['存储过程'],
    analysis: '存储过程可包含变量、IF、循环等控制流，预编译、可复用、减少网络交互。A 错误。' }
];
