/* ===== Linux/Shell题库：45道选择题（对齐菜鸟教程 / 鸟哥 / 联通运维岗笔试） ===== */
window.LINUX_QUESTIONS = [
  { id: 'LX_001', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '列出当前目录下所有文件（含隐藏文件）的命令是？',
    options: ['A. ls -a', 'B. ls -l', 'C. ls -d', 'D. ls -h'],
    answer: 'A', tags: ['ls', '文件管理'],
    analysis: 'ls -a 显示所有文件包括 . 开头的隐藏文件；-l 长格式；-h 人类可读大小。' },

  { id: 'LX_002', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '切换到用户主目录的命令是？',
    options: ['A. cd ~', 'B. cd /', 'C. cd ..', 'D. cd -'],
    answer: 'A', tags: ['cd', '目录'],
    analysis: 'cd ~ 或 cd 不带参数回到主目录；cd / 到根目录；cd .. 上一级；cd - 回到上一次目录。' },

  { id: 'LX_003', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '显示当前所在目录的绝对路径，用哪个命令？',
    options: ['A. pwd', 'B. whoami', 'C. dir', 'D. path'],
    answer: 'A', tags: ['pwd'],
    analysis: 'pwd (print working directory) 显示当前路径；whoami 显示当前用户名。' },

  { id: 'LX_004', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '递归创建多级目录，正确的命令是？',
    options: ['A. mkdir -p a/b/c', 'B. mkdir a/b/c', 'C. mkdir -r a/b/c', 'D. mkdir --all a/b/c'],
    answer: 'A', tags: ['mkdir'],
    analysis: 'mkdir -p 递归创建不存在的父目录；不加 -p 时父目录不存在会报错。' },

  { id: 'LX_005', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '删除空目录用 rmdir，删除非空目录用？',
    options: ['A. rm -r 目录', 'B. rmdir 目录', 'C. del 目录', 'D. remove 目录'],
    answer: 'A', tags: ['rm', '删除'],
    analysis: 'rm -r 递归删除目录及内容；rmdir 只能删空目录。删除需谨慎，rm -rf 极危险。' },

  { id: 'LX_006', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '复制文件 file1 到 /tmp 目录，正确的是？',
    options: ['A. cp file1 /tmp/', 'B. mv file1 /tmp/', 'C. copy file1 /tmp/', 'D. cp /tmp/ file1'],
    answer: 'A', tags: ['cp'],
    analysis: 'cp 源 目标 复制；mv 是移动/重命名；Linux 没有 copy 命令。' },

  { id: 'LX_007', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看文件内容的命令，错误的是？',
    options: ['A. ls 文件名', 'B. cat 文件名', 'C. less 文件名', 'D. more 文件名'],
    answer: 'A', tags: ['文件查看'],
    analysis: 'cat/less/more/tail/head 都能查看文件；ls 是列目录，不是看内容。' },

  { id: 'LX_008', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '实时跟踪日志文件新增内容，常用命令是？',
    options: ['A. tail -f 日志', 'B. head 日志', 'C. cat 日志', 'D. more 日志'],
    answer: 'A', tags: ['tail', '日志'],
    analysis: 'tail -f 持续输出文件末尾新增内容，是运维看日志最常用命令。' },

  { id: 'LX_009', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '在文件内容中搜索包含"error"的行，用？',
    options: ['A. grep error 文件名', 'B. find error', 'C. search error', 'D. cat error'],
    answer: 'A', tags: ['grep', '搜索'],
    analysis: 'grep 模式 文件 搜索文本；find 按文件名/属性查找文件。' },

  { id: 'LX_010', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '按文件名查找文件（在 /home 下找 *.log），用？',
    options: ['A. find /home -name "*.log"', 'B. grep "*.log" /home', 'C. ls /home *.log', 'D. locate -name'],
    answer: 'A', tags: ['find'],
    analysis: 'find 路径 -name 模式 按名称查找；grep 搜内容；ls 不能递归搜索。' },

  { id: 'LX_011', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看系统所有进程的完整信息，常用？',
    options: ['A. ps -ef', 'B. ls -l', 'C. df -h', 'D. du -sh'],
    answer: 'A', tags: ['ps', '进程'],
    analysis: 'ps -ef 或 ps aux 查看所有进程；df 看磁盘；du 看目录大小。' },

  { id: 'LX_012', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '实时动态查看 CPU/内存占用（类似任务管理器），用？',
    options: ['A. top', 'B. ps', 'C. netstat', 'D. df'],
    answer: 'A', tags: ['top', '监控'],
    analysis: 'top 实时刷新进程资源占用；ps 是静态快照。' },

  { id: 'LX_013', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看磁盘空间使用情况，用？',
    options: ['A. df -h', 'B. du -sh', 'C. free -h', 'D. top'],
    answer: 'A', tags: ['df', '磁盘'],
    analysis: 'df 看文件系统整体空间；du 看某个目录/文件占用；free 看内存。' },

  { id: 'LX_014', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看某目录占用的磁盘空间大小，用？',
    options: ['A. du -sh 目录', 'B. df -h 目录', 'C. ls -lh', 'D. du -a'],
    answer: 'A', tags: ['du', '磁盘'],
    analysis: 'du -sh 目录 统计目录总大小（人类可读）；df 看整盘。' },

  { id: 'LX_015', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看内存使用情况，用？',
    options: ['A. free -h', 'B. df -h', 'C. du -h', 'D. ps -h'],
    answer: 'A', tags: ['内存'],
    analysis: 'free -h 查看内存和 swap 使用；df/du 是磁盘。' },

  { id: 'LX_016', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看网络端口监听情况，常用？',
    options: ['A. netstat -tuln', 'B. top', 'C. ps -ef', 'D. ifconfig -a'],
    answer: 'A', tags: ['netstat', '网络'],
    analysis: 'netstat -tuln 列出 TCP/UDP 监听端口；ifconfig 看网卡 IP 配置。' },

  { id: 'LX_017', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看/配置网络接口 IP 地址，用？',
    options: ['A. ifconfig 或 ip addr', 'B. netstat', 'C. ping', 'D. route'],
    answer: 'A', tags: ['网络', 'ifconfig'],
    analysis: 'ifconfig 或 ip addr 查看网卡 IP；netstat 看端口；ping 测连通。' },

  { id: 'LX_018', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '测试到某主机的网络连通性，用？',
    options: ['A. ping 主机', 'B. telnet 主机', 'C. ssh 主机', 'D. curl 主机'],
    answer: 'A', tags: ['ping', '网络'],
    analysis: 'ping 发 ICMP 探测连通性；telnet/ssh 远程登录；curl 访问 URL。' },

  { id: 'LX_019', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '修改文件权限为 rwxr-xr-x（755），用？',
    options: ['A. chmod 755 文件', 'B. chmod 644 文件', 'C. chmod 777 文件', 'D. chmod 700 文件'],
    answer: 'A', tags: ['chmod', '权限'],
    analysis: '755 = 属主 rwx(7)、组 r-x(5)、其他 r-x(5)。644=rw-r--r--，777=所有人可读写执行。' },

  { id: 'LX_020', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '给脚本文件加上可执行权限，用？',
    options: ['A. chmod +x 脚本', 'B. chmod -x 脚本', 'C. chmod +w 脚本', 'D. chmod 777 脚本'],
    answer: 'A', tags: ['chmod', '权限'],
    analysis: 'chmod +x 添加执行权限（x=execute）；+w 加写；-x 去掉执行。' },

  { id: 'LX_021', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '编辑定时任务（crontab），用？',
    options: ['A. crontab -e', 'B. cron -e', 'C. crontab -l', 'D. at -e'],
    answer: 'A', tags: ['cron', '定时任务'],
    analysis: 'crontab -e 编辑定时任务，-l 查看，-r 删除。' },

  { id: 'LX_022', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'crontab 中 "0 2 * * * cmd" 表示？',
    options: ['A. 每天凌晨2点执行', 'B. 每2小时执行', 'C. 每周二执行', 'D. 每月2号执行'],
    answer: 'A', tags: ['cron'],
    analysis: '格式：分 时 日 月 周。0 2 * * * = 每天 2:00 执行。' },

  { id: 'LX_023', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看文件前 10 行内容，用？',
    options: ['A. head 文件', 'B. tail 文件', 'C. cat -10 文件', 'D. more 文件'],
    answer: 'A', tags: ['head'],
    analysis: 'head 默认显示前 10 行；tail 默认显示后 10 行；都可用 -n 指定行数。' },

  { id: 'LX_024', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '统计文件的行数，用？',
    options: ['A. wc -l 文件', 'B. wc -w 文件', 'C. wc -c 文件', 'D. wc -m 文件'],
    answer: 'A', tags: ['wc'],
    analysis: 'wc -l 行数、-w 单词数、-c 字节数、-m 字符数。' },

  { id: 'LX_025', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '管道符 | 的作用是？',
    options: ['A. 把前一个命令的输出作为后一个命令的输入', 'B. 并行执行两个命令', 'C. 注释', 'D. 重定向输出'],
    answer: 'A', tags: ['管道', '重定向'],
    analysis: '| 连接命令，如 ps -ef | grep java。> 是重定向输出到文件，< 是输入重定向。' },

  { id: 'LX_026', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '把命令输出重定向（覆盖）到文件，用？',
    options: ['A. cmd > 文件', 'B. cmd >> 文件', 'C. cmd < 文件', 'D. cmd | 文件'],
    answer: 'A', tags: ['重定向'],
    analysis: '> 覆盖写入；>> 追加写入；< 输入重定向；| 管道。' },

  { id: 'LX_027', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '终止某个进程，用？',
    options: ['A. kill PID', 'B. stop PID', 'C. end PID', 'D. quit PID'],
    answer: 'A', tags: ['kill', '进程'],
    analysis: 'kill PID 发信号终止进程；kill -9 PID 强制终止。' },

  { id: 'LX_028', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '压缩打包文件为 tar.gz，用？',
    options: ['A. tar -zcvf 包名.tar.gz 文件', 'B. tar -zxvf 包名', 'C. zip 文件', 'D. gzip 文件'],
    answer: 'A', tags: ['tar', '压缩'],
    analysis: 'tar -zcvf 打包压缩（z=gzip, c=create, v=verbose, f=file）；-zxvf 解压。' },

  { id: 'LX_029', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '解压 .tar.gz 文件，用？',
    options: ['A. tar -zxvf 包名.tar.gz', 'B. tar -zcvf 包名.tar.gz', 'C. unzip 包名', 'D. gunzip 包名'],
    answer: 'A', tags: ['tar', '压缩'],
    analysis: 'tar -zxvf 解压 tar.gz；unzip 解 zip；gunzip 解 .gz。' },

  { id: 'LX_030', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '远程登录另一台 Linux 主机，用？',
    options: ['A. ssh 用户@主机', 'B. telnet 主机', 'C. rlogin 主机', 'D. ftp 主机'],
    answer: 'A', tags: ['ssh', '远程'],
    analysis: 'ssh 是加密的远程登录协议（默认端口22）；telnet 明文不安全。' },

  { id: 'LX_031', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '在主机间安全复制文件，用？',
    options: ['A. scp 文件 用户@主机:路径', 'B. cp 文件 主机', 'C. rcp', 'D. wget 文件'],
    answer: 'A', tags: ['scp', '远程'],
    analysis: 'scp 基于 ssh 安全复制文件；wget 从网络下载文件。' },

  { id: 'LX_032', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '从 URL 下载文件到本地，用？',
    options: ['A. wget URL', 'B. scp URL', 'C. ftp URL', 'D. download URL'],
    answer: 'A', tags: ['wget', '网络'],
    analysis: 'wget 或 curl -O 可下载文件；scp 是主机间复制。' },

  { id: 'LX_033', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'awk 命令的主要用途是？',
    options: ['A. 按列处理/格式化文本', 'B. 文本替换', 'C. 排序', 'D. 统计行数'],
    answer: 'A', tags: ['awk'],
    analysis: 'awk 按列提取、处理文本（如 awk \'{print $1}\'）；sed 做替换；sort 排序。' },

  { id: 'LX_034', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'sed 命令的主要用途是？',
    options: ['A. 文本替换/编辑', 'B. 按列处理', 'C. 排序', 'D. 去重'],
    answer: 'A', tags: ['sed'],
    analysis: 'sed 流编辑器做替换（s/旧/新/g）、删除行等；awk 按列处理；sort/uniq 排序去重。' },

  { id: 'LX_035', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '对文本内容排序，用？',
    options: ['A. sort', 'B. uniq', 'C. wc', 'D. grep'],
    answer: 'A', tags: ['sort'],
    analysis: 'sort 排序；uniq 对相邻重复行去重（常配合 sort 使用）。' },

  { id: 'LX_036', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '去除相邻重复行，用？',
    options: ['A. uniq', 'B. sort', 'C. grep', 'D. sed'],
    answer: 'A', tags: ['uniq'],
    analysis: 'uniq 只能去除相邻重复行，通常先 sort 再 uniq 才能全量去重。' },

  { id: 'LX_037', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '查看并管理 systemd 服务状态，用？',
    options: ['A. systemctl status 服务名', 'B. service status 服务名', 'C. ps 服务名', 'D. start 服务名'],
    answer: 'A', tags: ['systemctl', '服务'],
    analysis: 'systemctl start/stop/status/restart 服务名 管理 systemd 服务。' },

  { id: 'LX_038', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'vi/vim 中，从编辑模式保存并退出，应输入？',
    options: ['A. :wq', 'B. :q', 'C. :w', 'D. :q!'],
    answer: 'A', tags: ['vim'],
    analysis: ':wq 保存退出；:q 不保存退出（有改动会提示）；:q! 强制不保存退出；:w 只保存。' },

  { id: 'LX_039', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '查看内核版本和系统信息，用？',
    options: ['A. uname -a', 'B. pwd', 'C. who', 'D. hostname'],
    answer: 'A', tags: ['系统信息'],
    analysis: 'uname -a 显示内核版本等；hostname 显示主机名；who 看登录用户。' },

  { id: 'LX_040', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '查看命令的帮助文档，用？',
    options: ['A. man 命令', 'B. help 命令 都行，man 最全', 'C. read 命令', 'D. doc 命令'],
    answer: 'B', tags: ['帮助'],
    analysis: 'man 命令查看完整手册（最常用），help 命令查看内建命令帮助。' },

  { id: 'LX_041', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: '切换用户身份（切换到 root）用？',
    options: ['A. su 或 sudo', 'B. login', 'C. passwd', 'D. useradd'],
    answer: 'A', tags: ['用户管理'],
    analysis: 'su 切换用户，sudo 以管理员权限执行命令；passwd 改密码；useradd 建用户。' },

  { id: 'LX_042', module: 'linux', type: 'choice', difficulty: 1, source: '菜鸟教程',
    question: '查看当前登录用户名，用？',
    options: ['A. whoami', 'B. pwd', 'C. id', 'D. uname'],
    answer: 'A', tags: ['用户管理'],
    analysis: 'whoami 显示当前用户名；id 显示 uid/gid；pwd 显示路径。' },

  { id: 'LX_043', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'echo $HOME 的作用是？',
    options: ['A. 输出环境变量 HOME 的值（主目录路径）', 'B. 创建 HOME 变量', 'C. 切换目录', 'D. 显示所有变量'],
    answer: 'A', tags: ['环境变量', 'Shell'],
    analysis: '$变量名 引用变量，echo $HOME 打印主目录路径；env 查看所有环境变量。' },

  { id: 'LX_044', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'Shell 脚本中，注释行的符号是？',
    options: ['A. #', 'B. //', 'C. /* */', 'D. --'],
    answer: 'A', tags: ['Shell脚本'],
    analysis: 'Shell 用 # 注释（首行 #!/bin/bash 是 shebang，不是普通注释）；// 和 /* */ 是 C 系语言注释。' },

  { id: 'LX_045', module: 'linux', type: 'choice', difficulty: 2, source: '菜鸟教程',
    question: 'Linux 中，普通文件权限 rwxr-xr-x 对应数字模式是？',
    options: ['A. 755', 'B. 644', 'C. 555', 'D. 777'],
    answer: 'A', tags: ['权限'],
    analysis: 'r=4,w=2,x=1。rwx=7，r-x=5，r-x=5 → 755。' }
];
