/* ===== Python题库：80道选择题 + 15道编程题 ===== */
window.PY_QUESTIONS = [
  // ---------- 选择题 ----------
  { id: 'P_001', module: 'python', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'Python 中，下列哪个是合法的变量名？',
    options: ['A. 2name', 'B. _name', 'C. my-name', 'D. class'],
    answer: 'B', tags: ['基础语法'],
    analysis: '变量名由字母、数字、下划线组成，不能以数字开头，不能是关键字。_name 合法；class 是关键字。' },

  { id: 'P_002', module: 'python', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'print(type(3.14)) 的输出是？',
    options: ['A. <class \'int\'>', 'B. <class \'float\'>', 'C. <class \'str\'>', 'D. <class \'double\'>'],
    answer: 'B', tags: ['数据类型'],
    analysis: '3.14 是浮点数，类型为 float。Python 没有 double 类型。' },

  { id: 'P_003', module: 'python', type: 'choice', difficulty: 1, source: '牛客网',
    question: '表达式 5 // 2 的结果是？',
    options: ['A. 2.5', 'B. 2', 'C. 3', 'D. 2.0'],
    answer: 'B', tags: ['运算符'],
    analysis: '// 是地板除（整除），向下取整，5 // 2 = 2。/ 是普通除法返回浮点数 2.5。' },

  { id: 'P_004', module: 'python', type: 'choice', difficulty: 1, source: '牛客网',
    question: '表达式 2 ** 3 的结果是？',
    options: ['A. 6', 'B. 8', 'C. 9', 'D. 5'],
    answer: 'B', tags: ['运算符'],
    analysis: '** 是幂运算，2 ** 3 = 2 的 3 次方 = 8。' },

  { id: 'P_005', module: 'python', type: 'choice', difficulty: 1, source: '牛客网',
    question: '表达式 10 % 3 的结果是？',
    options: ['A. 3', 'B. 1', 'C. 0', 'D. 2'],
    answer: 'B', tags: ['运算符'],
    analysis: '% 是取余，10 ÷ 3 = 3 余 1，所以结果是 1。' },

  { id: 'P_006', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'Python 中，字符串可以用哪几种引号表示？',
    options: ['A. 只能用单引号', 'B. 只能用双引号', 'C. 单引号、双引号、三引号均可', 'D. 只能用三引号'],
    answer: 'C', tags: ['字符串'],
    analysis: 'Python 字符串可用单引号、双引号或三引号（三引号支持多行字符串）。' },

  { id: 'P_007', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'len("hello") 的结果是？',
    options: ['A. 4', 'B. 5', 'C. 6', 'D. 报错'],
    answer: 'B', tags: ['字符串'],
    analysis: 'len() 返回字符串长度，"hello" 有 5 个字符。' },

  { id: 'P_008', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '"hello".upper() 的结果是？',
    options: ['A. "HELLO"', 'B. "Hello"', 'C. "hello"', 'D. 报错'],
    answer: 'A', tags: ['字符串'],
    analysis: 'upper() 把字符串转为全大写，"hello".upper() = "HELLO"。' },

  { id: 'P_009', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '字符串 "a,b,c".split(",") 的结果是？',
    options: ['A. "abc"', 'B. ["a", "b", "c"]', 'C. "a b c"', 'D. ("a", "b", "c")'],
    answer: 'B', tags: ['字符串'],
    analysis: 'split(",") 按逗号分割字符串，返回列表 ["a", "b", "c"]。' },

  { id: 'P_010', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是正确的列表定义？',
    options: ['A. [1, 2, 3]', 'B. {1, 2, 3}', 'C. (1, 2, 3)', 'D. <1, 2, 3>'],
    answer: 'A', tags: ['列表'],
    analysis: '[] 是列表；{} 是集合或字典；() 是元组。' },

  { id: 'P_011', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [1, 2, 3]; list.append(4) 后 list 是？',
    options: ['A. [1, 2, 3, 4]', 'B. [4, 1, 2, 3]', 'C. [1, 2, 3, [4]]', 'D. 报错'],
    answer: 'A', tags: ['列表'],
    analysis: 'append() 在列表末尾追加一个元素，结果 [1, 2, 3, 4]。' },

  { id: 'P_012', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [3, 1, 2]; list.sort() 后 list 是？',
    options: ['A. [3, 2, 1]', 'B. [1, 2, 3]', 'C. [3, 1, 2]', 'D. 报错'],
    answer: 'B', tags: ['列表'],
    analysis: 'sort() 原地排序（默认升序），列表变为 [1, 2, 3]。' },

  { id: 'P_013', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [1, 2, 3, 4]; list[1:3] 的结果是？',
    options: ['A. [1, 2]', 'B. [2, 3]', 'C. [2, 3, 4]', 'D. [1, 2, 3]'],
    answer: 'B', tags: ['列表', '切片'],
    analysis: '切片 [1:3] 取下标 1 到 2（不含 3），即 [2, 3]。切片是左闭右开区间。' },

  { id: 'P_014', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [1, 2, 3]; list[-1] 的值是？',
    options: ['A. 1', 'B. 2', 'C. 3', 'D. 报错'],
    answer: 'C', tags: ['列表'],
    analysis: '负数下标从末尾开始计数，list[-1] 是最后一个元素 3。' },

  { id: 'P_015', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是正确的字典定义？',
    options: ['A. {"name": "Tom", "age": 20}', 'B. {"name", "Tom"}', 'C. ["name", "Tom"]', 'D. ("name": "Tom")'],
    answer: 'A', tags: ['字典'],
    analysis: '字典用 {} 表示键值对，{"name": "Tom", "age": 20} 正确。' },

  { id: 'P_016', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'd = {"a": 1}; d["b"] = 2 后 d 是？',
    options: ['A. {"a": 1}', 'B. {"a": 1, "b": 2}', 'C. 报错', 'D. {"b": 2}'],
    answer: 'B', tags: ['字典'],
    analysis: '给不存在的键赋值会添加新键值对，d 变为 {"a": 1, "b": 2}。' },

  { id: 'P_017', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'd = {"a": 1}; d.get("b", 0) 的结果是？',
    options: ['A. 报错', 'B. 0', 'C. None', 'D. 1'],
    answer: 'B', tags: ['字典'],
    analysis: 'get(key, default) 在键不存在时返回默认值 0，不会报错（d["b"] 才会报 KeyError）。' },

  { id: 'P_018', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '元组和列表的主要区别是？',
    options: ['A. 元组不可变，列表可变', 'B. 列表不可变，元组可变', 'C. 没有区别', 'D. 元组只能用整数'],
    answer: 'A', tags: ['元组'],
    analysis: '元组（tuple）创建后不可修改（不可变），列表（list）可变。元组用 () 定义。' },

  { id: 'P_019', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 's = {1, 2, 3}; s 的类型是？',
    options: ['A. 列表', 'B. 集合', 'C. 字典', 'D. 元组'],
    answer: 'B', tags: ['集合'],
    analysis: '{} 内含逗号分隔的元素（无键值对）是集合（set），元素唯一、无序。空 {} 是字典。' },

  { id: 'P_020', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '集合的特点，下列说法正确的是？',
    options: ['A. 元素有序', 'B. 元素不可重复', 'C. 元素可重复', 'D. 用 [] 定义'],
    answer: 'B', tags: ['集合'],
    analysis: '集合元素唯一（不可重复）且无序，用 set() 或 {} 定义，可用于去重。' },

  { id: 'P_021', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'range(5) 表示？',
    options: ['A. 0,1,2,3,4,5', 'B. 0,1,2,3,4', 'C. 1,2,3,4,5', 'D. 5'],
    answer: 'B', tags: ['range'],
    analysis: 'range(5) 生成 0 到 4 的序列（左闭右开，不含 5）。' },

  { id: 'P_022', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'range(1, 10, 2) 表示？',
    options: ['A. 1,3,5,7,9', 'B. 1,2,3,4,5', 'C. 2,4,6,8,10', 'D. 1,4,7'],
    answer: 'A', tags: ['range'],
    analysis: 'range(start, stop, step)，从 1 到 9 步长 2，即 1,3,5,7,9。' },

  { id: 'P_023', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'for i in range(3): print(i) 输出是？',
    options: ['A. 1 2 3', 'B. 0 1 2', 'C. 0 1 2 3', 'D. 1 2'],
    answer: 'B', tags: ['循环'],
    analysis: 'range(3) 是 0,1,2，依次输出，每个占一行：0 1 2。' },

  { id: 'P_024', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是 Python 中定义函数的关键字？',
    options: ['A. function', 'B. def', 'C. func', 'D. define'],
    answer: 'B', tags: ['函数'],
    analysis: 'Python 用 def 定义函数，语法 def 函数名(参数):。' },

  { id: 'P_025', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'def add(a, b=10): return a + b; 调用 add(5) 返回？',
    options: ['A. 5', 'B. 15', 'C. 10', 'D. 报错'],
    answer: 'B', tags: ['函数'],
    analysis: 'b 有默认值 10，add(5) 等价于 add(5, 10)，返回 15。' },

  { id: 'P_026', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'lambda 表达式的作用是？',
    options: ['A. 定义类', 'B. 定义匿名函数', 'C. 定义变量', 'D. 导入模块'],
    answer: 'B', tags: ['函数'],
    analysis: 'lambda 用于创建匿名函数，如 f = lambda x: x * 2。' },

  { id: 'P_027', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是正确的 if 语句写法？',
    options: ['A. if x > 0 { }', 'B. if x > 0:', 'C. if (x > 0) { }', 'D. if x > 0 then'],
    answer: 'B', tags: ['条件语句'],
    analysis: 'Python 的 if 语句用冒号结尾，代码块靠缩进，无花括号。' },

  { id: 'P_028', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'elif 的作用是？',
    options: ['A. 结束 if', 'B. 多条件分支（else if）', 'C. 定义函数', 'D. 循环'],
    answer: 'B', tags: ['条件语句'],
    analysis: 'elif 是 else if 的缩写，用于多条件分支判断。' },

  { id: 'P_029', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'while 循环的 else 子句什么时候执行？',
    options: ['A. 循环至少执行一次后', 'B. 循环条件为假（未被 break 打断）时', 'C. 永不执行', 'D. 循环被 break 时'],
    answer: 'B', tags: ['循环'],
    analysis: 'while/for 的 else 子句在循环正常结束（条件为假，未 break）时执行；被 break 中断则不执行。' },

  { id: 'P_030', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'break 和 continue 的区别是？',
    options: ['A. 没区别', 'B. break 终止整个循环，continue 跳过本次', 'C. continue 终止循环', 'D. break 跳过本次'],
    answer: 'B', tags: ['循环'],
    analysis: 'break 终止整个循环；continue 跳过本次循环剩余代码，继续下一次迭代。' },

  { id: 'P_031', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '列表推导式 [x*2 for x in range(3)] 的结果是？',
    options: ['A. [0, 2, 4]', 'B. [0, 1, 2]', 'C. [2, 4, 6]', 'D. (0, 2, 4)'],
    answer: 'A', tags: ['列表推导式'],
    analysis: 'range(3) 是 0,1,2，每个乘 2 得 0,2,4。' },

  { id: 'P_032', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: '[x for x in range(10) if x % 2 == 0] 的结果是？',
    options: ['A. [0,2,4,6,8]', 'B. [1,3,5,7,9]', 'C. [0,2,4,6,8,10]', 'D. [2,4,6,8,10]'],
    answer: 'A', tags: ['列表推导式'],
    analysis: '带 if 过滤条件的推导式，只保留偶数：0,2,4,6,8。' },

  { id: 'P_033', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'print("a", "b", sep="-") 输出是？',
    options: ['A. "a b"', 'B. "a-b"', 'C. "ab"', 'D. 报错'],
    answer: 'B', tags: ['print'],
    analysis: 'sep 参数指定多个参数间的分隔符，默认是空格，这里指定为 "-"，输出 a-b。' },

  { id: 'P_034', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'print("Hi", end="") 的作用是？',
    options: ['A. 换行输出', 'B. 输出后不换行', 'C. 不输出', 'D. 报错'],
    answer: 'B', tags: ['print'],
    analysis: 'end 参数指定输出结尾字符，默认 "\\n"（换行），设为 "" 则输出后不换行。' },

  { id: 'P_035', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int("123") 的结果是？',
    options: ['A. "123"', 'B. 123', 'C. 123.0', 'D. 报错'],
    answer: 'B', tags: ['类型转换'],
    analysis: 'int() 把字符串转为整数 123。' },

  { id: 'P_036', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'str(123) 的结果是？',
    options: ['A. 123', 'B. "123"', 'C. 123.0', 'D. 报错'],
    answer: 'B', tags: ['类型转换'],
    analysis: 'str() 把整数转为字符串 "123"。' },

  { id: 'P_037', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'float("3.5") + 1 的结果是？',
    options: ['A. "3.51"', 'B. 4.5', 'C. "4.5"', 'D. 报错'],
    answer: 'B', tags: ['类型转换'],
    analysis: 'float("3.5") = 3.5，加 1 得 4.5。' },

  { id: 'P_038', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'bool(0) 和 bool([]) 的值分别是？',
    options: ['A. True, True', 'B. False, False', 'C. True, False', 'D. False, True'],
    answer: 'B', tags: ['数据类型'],
    analysis: '0、空字符串、空列表、空字典、None 都是假值，bool() 为 False。' },

  { id: 'P_039', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'x = 5; x == "5" 的结果是？',
    options: ['A. True', 'B. False', 'C. 报错', 'D. None'],
    answer: 'B', tags: ['运算符'],
    analysis: '整数 5 和字符串 "5" 类型不同，== 比较结果为 False（不会自动类型转换）。' },

  { id: 'P_040', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 3 > 2 and 4 < 5 的结果是？',
    options: ['A. True', 'B. False', 'C. 报错', 'D. None'],
    answer: 'A', tags: ['运算符'],
    analysis: '3 > 2 为 True，4 < 5 为 True，and 两边都为 True，结果为 True。' },

  { id: 'P_041', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'not True 的结果是？',
    options: ['A. True', 'B. False', 'C. None', 'D. 0'],
    answer: 'B', tags: ['运算符'],
    analysis: 'not 是逻辑非，not True = False。' },

  { id: 'P_042', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'in 运算符的作用是？',
    options: ['A. 判断元素是否在序列中', 'B. 赋值', 'C. 定义循环', 'D. 导入模块'],
    answer: 'A', tags: ['运算符'],
    analysis: 'in 判断成员关系，如 2 in [1, 2, 3] 为 True。' },

  { id: 'P_043', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '"abc" + "def" 的结果是？',
    options: ['A. "abcdef"', 'B. "abc def"', 'C. 报错', 'D. ["abc", "def"]'],
    answer: 'A', tags: ['字符串'],
    analysis: '字符串 + 是拼接，"abc" + "def" = "abcdef"。' },

  { id: 'P_044', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '"abc" * 2 的结果是？',
    options: ['A. "abcabc"', 'B. "aabbcc"', 'C. 报错', 'D. 6'],
    answer: 'A', tags: ['字符串'],
    analysis: '字符串 * 整数表示重复拼接，"abc" * 2 = "abcabc"。' },

  { id: 'P_045', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '字符串格式化 f"1+1={1+1}" 的结果是？',
    options: ['A. "1+1=2"', 'B. "1+1={1+1}"', 'C. 报错', 'D. "1+1=1+1"'],
    answer: 'A', tags: ['字符串', '格式化'],
    analysis: 'f-string 会计算 {} 内表达式，f"1+1={1+1}" = "1+1=2"。' },

  { id: 'P_046', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: '列表 [1, 2, 3] + [4, 5] 的结果是？',
    options: ['A. [1, 2, 3, 4, 5]', 'B. [1, 2, 3, [4, 5]]', 'C. 6', 'D. 报错'],
    answer: 'A', tags: ['列表'],
    analysis: '列表 + 是拼接（合并），[1,2,3] + [4,5] = [1,2,3,4,5]。' },

  { id: 'P_047', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下哪个操作不会修改原列表？',
    options: ['A. list.append(1)', 'B. list.sort()', 'C. sorted(list)', 'D. list.pop()'],
    answer: 'C', tags: ['列表'],
    analysis: 'sorted(list) 返回新排序列表，不修改原列表；append/sort/pop 都是原地操作。' },

  { id: 'P_048', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [1, 2, 3]; del list[1] 后 list 是？',
    options: ['A. [1, 3]', 'B. [1, 2]', 'C. [2, 3]', 'D. [1, 2, 3]'],
    answer: 'A', tags: ['列表'],
    analysis: 'del list[1] 删除下标 1 的元素（值 2），剩下 [1, 3]。' },

  { id: 'P_049', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'list = [1, 2, 3]; list.pop() 返回并删除的元素是？',
    options: ['A. 1', 'B. 2', 'C. 3', 'D. 报错'],
    answer: 'C', tags: ['列表'],
    analysis: 'pop() 默认删除并返回最后一个元素 3。' },

  { id: 'P_050', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'tuple = (1, 2, 3); tuple[0] = 5 会？',
    options: ['A. 正常修改', 'B. 报 TypeError（元组不可变）', 'C. 变成 (5,2,3)', 'D. 报语法错误'],
    answer: 'B', tags: ['元组'],
    analysis: '元组不可变，不能对其元素赋值，会抛出 TypeError。' },

  { id: 'P_051', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'd = {"a": 1, "b": 2}; d.keys() 返回？',
    options: ['A. ["a", "b"]', 'B. dict_keys([\'a\', \'b\'])', 'C. [1, 2]', 'D. "ab"'],
    answer: 'B', tags: ['字典'],
    analysis: 'keys() 返回所有键的视图对象 dict_keys([\'a\', \'b\'])，可遍历或 list() 转换。' },

  { id: 'P_052', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'd = {"a": 1, "b": 2}; "a" in d 的结果是？',
    options: ['A. True', 'B. False', 'C. 报错', 'D. 1'],
    answer: 'A', tags: ['字典'],
    analysis: 'in 判断键是否在字典中，"a" 是键，返回 True。' },

  { id: 'P_053', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'Python 中，函数的参数传递是？',
    options: ['A. 值传递', 'B. 引用传递', 'C. 对象引用传递（传对象的引用）', 'D. 指针传递'],
    answer: 'C', tags: ['函数'],
    analysis: 'Python 传的是对象的引用，但不可变对象（如 int、str）修改会创建新对象，表现类似值传递；可变对象（list、dict）在函数内修改会影响原对象。' },

  { id: 'P_054', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'def f(x): x.append(1); a = []; f(a); print(a) 输出是？',
    options: ['A. []', 'B. [1]', 'C. 报错', 'D. None'],
    answer: 'B', tags: ['函数', '可变对象'],
    analysis: '列表是可变对象，函数内 append 会修改原列表，所以 a 变为 [1]。' },

  { id: 'P_055', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'def f(x): x = 10; a = 5; f(a); print(a) 输出是？',
    options: ['A. 10', 'B. 5', 'C. 报错', 'D. None'],
    answer: 'B', tags: ['函数', '不可变对象'],
    analysis: 'int 是不可变对象，函数内 x = 10 只是重新绑定局部变量，不影响外面的 a，a 仍为 5。' },

  { id: 'P_056', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '全局变量在函数内要修改需用什么关键字声明？',
    options: ['A. global', 'B. local', 'C. static', 'D. extern'],
    answer: 'A', tags: ['函数', '作用域'],
    analysis: '函数内要修改全局变量需用 global 声明，否则赋值会创建局部变量。' },

  { id: 'P_057', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是导入模块的正确方式？',
    options: ['A. import math', 'B. include math', 'C. using math', 'D. require math'],
    answer: 'A', tags: ['模块'],
    analysis: 'Python 用 import 导入模块，如 import math。' },

  { id: 'P_058', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'from math import sqrt 后如何调用 sqrt？',
    options: ['A. math.sqrt()', 'B. sqrt()', 'C. import sqrt()', 'D. math::sqrt()'],
    answer: 'B', tags: ['模块'],
    analysis: 'from math import sqrt 直接导入 sqrt 函数，调用时直接 sqrt()，无需 math. 前缀。' },

  { id: 'P_059', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'import math; math.sqrt(16) 的结果是？',
    options: ['A. 4', 'B. 4.0', 'C. 8', 'D. 256'],
    answer: 'B', tags: ['模块'],
    analysis: 'math.sqrt 返回浮点数，sqrt(16) = 4.0。' },

  { id: 'P_060', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'Python 中捕获异常的关键字是？',
    options: ['A. try/except', 'B. try/catch', 'C. try/finally 只有', 'D. catch/except'],
    answer: 'A', tags: ['异常'],
    analysis: 'Python 用 try/except 捕获异常，try/catch 是 Java/C++ 语法。' },

  { id: 'P_061', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'try: x = 1/0 \nexcept ZeroDivisionError: print("error") 输出是？',
    options: ['A. 报错', 'B. "error"', 'C. 无输出', 'D. 无限循环'],
    answer: 'B', tags: ['异常'],
    analysis: '1/0 抛出 ZeroDivisionError，被 except 捕获，输出 "error"。' },

  { id: 'P_062', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'finally 子句的作用是？',
    options: ['A. 只在异常时执行', 'B. 无论是否异常都执行', 'C. 只在成功时执行', 'D. 不执行'],
    answer: 'B', tags: ['异常'],
    analysis: 'finally 子句无论是否发生异常都会执行，常用于释放资源、关闭文件。' },

  { id: 'P_063', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '打开文件推荐的写法是？',
    options: ['A. f = open("a.txt")', 'B. with open("a.txt") as f:', 'C. open "a.txt"', 'D. read "a.txt"'],
    answer: 'B', tags: ['文件操作'],
    analysis: 'with open() as f 是上下文管理器写法，自动关闭文件，即使发生异常也不会泄漏。' },

  { id: 'P_064', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '读取文件全部内容的方法？',
    options: ['A. f.read()', 'B. f.readline() 一次全读', 'C. f.load()', 'D. f.open()'],
    answer: 'A', tags: ['文件操作'],
    analysis: 'f.read() 读取整个文件内容为字符串；f.readline() 一次只读一行。' },

  { id: 'P_065', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'with open("a.txt", "w") as f: f.write("hi") 中 "w" 表示？',
    options: ['A. 只读', 'B. 写入（覆盖）', 'C. 追加', 'D. 二进制读'],
    answer: 'B', tags: ['文件操作'],
    analysis: '"w" 写入模式，覆盖原内容；"r" 读；"a" 追加；"r+" 读写。' },

  { id: 'P_066', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是 Python 中定义类的关键字？',
    options: ['A. class', 'B. struct', 'C. object', 'D. type'],
    answer: 'A', tags: ['类'],
    analysis: 'Python 用 class 定义类，语法 class ClassName:。' },

  { id: 'P_067', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '类的构造方法 __init__ 中，self 代表？',
    options: ['A. 类本身', 'B. 当前实例对象', 'C. 父类', 'D. 模块'],
    answer: 'B', tags: ['类'],
    analysis: 'self 代表当前实例对象，用于访问实例属性和方法。' },

  { id: 'P_068', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'class Dog:\n    def __init__(self, name):\n        self.name = name\nd = Dog("旺财")\nprint(d.name) 输出是？',
    options: ['A. name', 'B. 旺财', 'C. Dog', 'D. 报错'],
    answer: 'B', tags: ['类'],
    analysis: '__init__ 中 self.name = name 把参数赋给实例属性，d.name 为 "旺财"。' },

  { id: 'P_069', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '类的继承，定义子类时正确的写法是？',
    options: ['A. class Child(Parent):', 'B. class Child extends Parent:', 'C. class Child : Parent', 'D. class Child -> Parent'],
    answer: 'A', tags: ['类', '继承'],
    analysis: 'Python 继承语法 class 子类(父类):。' },

  { id: 'P_070', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'Python 中 @staticmethod 修饰的方法是？',
    options: ['A. 实例方法', 'B. 静态方法（无需 self）', 'C. 私有方法', 'D. 类方法'],
    answer: 'B', tags: ['类'],
    analysis: '@staticmethod 定义静态方法，不接收 self，可通过类或实例调用。@classmethod 是类方法，接收 cls。' },

  { id: 'P_071', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '判断一个对象类型用哪个函数？',
    options: ['A. type()', 'B. typeof()', 'C. instanceof()', 'D. class()'],
    answer: 'A', tags: ['内置函数'],
    analysis: 'type() 返回对象类型；isinstance(obj, type) 也可判断类型。' },

  { id: 'P_072', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'id() 函数返回的是？',
    options: ['A. 对象的内存地址标识', 'B. 对象的值', 'C. 对象的类型', 'D. 对象的长度'],
    answer: 'A', tags: ['内置函数'],
    analysis: 'id() 返回对象在内存中的唯一标识（地址），可比较两个变量是否指向同一对象。' },

  { id: 'P_073', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'enumerate(["a", "b"]) 的作用是？',
    options: ['A. 返回元素值', 'B. 返回 (索引, 值) 对', 'C. 返回索引', 'D. 排序'],
    answer: 'B', tags: ['内置函数'],
    analysis: 'enumerate 返回带索引的迭代器，每次产生 (索引, 元素) 元组。' },

  { id: 'P_074', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'zip([1, 2], ["a", "b"]) 的结果是？',
    options: ['A. [1, 2, "a", "b"]', 'B. [(1, "a"), (2, "b")]', 'C. {1: "a", 2: "b"}', 'D. 报错'],
    answer: 'B', tags: ['内置函数'],
    analysis: 'zip 把多个可迭代对象按位置打包成元组，list(zip(...)) 得 [(1, "a"), (2, "b")]。' },

  { id: 'P_075', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'map(lambda x: x * 2, [1, 2, 3]) 经 list() 后是？',
    options: ['A. [2, 4, 6]', 'B. [1, 2, 3]', 'C. 报错', 'D. (2, 4, 6)'],
    answer: 'A', tags: ['内置函数'],
    analysis: 'map 对每个元素应用函数，list(map(...)) 得 [2, 4, 6]。' },

  { id: 'P_076', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'filter(lambda x: x > 1, [0, 1, 2, 3]) 经 list() 后是？',
    options: ['A. [2, 3]', 'B. [0, 1]', 'C. [1, 2, 3]', 'D. [0, 1, 2, 3]'],
    answer: 'A', tags: ['内置函数'],
    analysis: 'filter 保留函数返回 True 的元素，x > 1 的只有 2, 3。' },

  { id: 'P_077', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'Python 的缩进作用是什么？',
    options: ['A. 无意义，仅美观', 'B. 决定代码块结构', 'C. 表示注释', 'D. 表示字符串'],
    answer: 'B', tags: ['基础语法'],
    analysis: 'Python 用缩进表示代码块（如 if、循环、函数体），缩进不一致会导致 IndentationError。' },

  { id: 'P_078', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'Python 中的单行注释符号是？',
    options: ['A. //', 'B. #', 'C. /* */', 'D. --'],
    answer: 'B', tags: ['基础语法'],
    analysis: 'Python 单行注释用 #，多行可用三引号字符串（严格说是文档字符串）。' },

  { id: 'P_079', module: 'python', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个表达式的结果是 None？',
    options: ['A. print("hi") 的返回值', 'B. 0', 'C. ""', 'D. []'],
    answer: 'A', tags: ['内置函数'],
    analysis: 'print() 函数没有返回值（返回 None）。0、""、[] 是假值但不是 None。' },

  { id: 'P_080', module: 'python', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'Python 中，列表和字典的深拷贝应使用哪个模块？',
    options: ['A. copy.deepcopy', 'B. copy.copy 就是深拷贝', 'C. os.copy', 'D. sys.copy'],
    answer: 'A', tags: ['模块', '拷贝'],
    analysis: 'copy.deepcopy 做深拷贝（递归复制嵌套对象）；copy.copy 是浅拷贝；直接赋值只是引用。' },

  // ---------- 编程题 ----------
  { id: 'P_P01', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '给定一个整数数组 nums 和一个目标值 target，返回数组中和为 target 的两个数的下标（两数之和）。',
    tags: ['数组', '哈希表'],
    answer: 'def two_sum(nums, target):\n    d = {}\n    for i, x in enumerate(nums):\n        if target - x in d:\n            return [d[target - x], i]\n        d[x] = i\n    return []',
    analysis: '用字典记录每个数及其下标，遍历时检查 target - x 是否已出现，O(n) 时间。' },

  { id: 'P_P02', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '反转一个字符串（返回反转后的字符串）。',
    tags: ['字符串'],
    answer: 'def reverse_string(s):\n    return s[::-1]',
    analysis: '切片 [::-1] 以步长 -1 从后向前取字符，实现反转。也可用 "".join(reversed(s))。' },

  { id: 'P_P03', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '判断一个字符串中的括号是否有效（()[]{} 匹配）。',
    tags: ['栈', '字符串'],
    answer: 'def is_valid(s):\n    stack = []\n    pairs = {\')\': \'(\', \']\': \'[\', \'}\': \'{\'}\n    for c in s:\n        if c in "([{":\n            stack.append(c)\n        else:\n            if not stack or stack.pop() != pairs[c]:\n                return False\n    return not stack',
    analysis: '用栈匹配括号：左括号入栈，右括号检查栈顶是否匹配。最后栈空则有效。' },

  { id: 'P_P04', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '判断一个整数是否为回文数。',
    tags: ['数学'],
    answer: 'def is_palindrome(x):\n    if x < 0:\n        return False\n    return str(x) == str(x)[::-1]',
    analysis: '负数不是回文。转字符串后与反转字符串比较即可。' },

  { id: 'P_P05', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '给定一个只包含 0 和 1 的数组，返回 1 的最大连续个数。',
    tags: ['数组'],
    answer: 'def find_max_consecutive_ones(nums):\n    cur = best = 0\n    for x in nums:\n        cur = cur + 1 if x == 1 else 0\n        best = max(best, cur)\n    return best',
    analysis: '遍历计数连续的 1，遇到 0 就清零，记录历史最大值。' },

  { id: 'P_P06', module: 'python', type: 'coding', difficulty: 1, source: 'LeetCode Easy',
    question: '实现 FizzBuzz：1 到 n，被 3 整除输出 Fizz，被 5 整除输出 Buzz，同时被整除输出 FizzBuzz，否则输出数字本身。',
    tags: ['循环'],
    answer: 'def fizz_buzz(n):\n    res = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            res.append("FizzBuzz")\n        elif i % 3 == 0:\n            res.append("Fizz")\n        elif i % 5 == 0:\n            res.append("Buzz")\n        else:\n            res.append(str(i))\n    return res',
    analysis: '按优先级判断：先判 15 的倍数（同时 3 和 5），再分别判 3、5 的倍数。' },

  { id: 'P_P07', module: 'python', type: 'coding', difficulty: 1, source: '牛客网',
    question: '计算一个数的阶乘 n!。',
    tags: ['递归', '循环'],
    answer: 'def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n\n# 递归版：\ndef factorial_rec(n):\n    return 1 if n <= 1 else n * factorial_rec(n - 1)',
    analysis: '循环累乘 2 到 n，或递归 n! = n * (n-1)!。' },

  { id: 'P_P08', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '给定一个列表，去重并保持原顺序。',
    tags: ['列表', '去重'],
    answer: 'def unique(seq):\n    seen = set()\n    res = []\n    for x in seq:\n        if x not in seen:\n            seen.add(x)\n            res.append(x)\n    return res',
    analysis: '用集合记录已见元素，只保留第一次出现的元素，保持原顺序。' },

  { id: 'P_P09', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '统计一个字符串中每个字符出现的次数，返回字典。',
    tags: ['字符串', '字典'],
    answer: 'def char_count(s):\n    from collections import Counter\n    return dict(Counter(s))',
    analysis: 'Counter 直接统计字符频次。也可手写：遍历字符用字典累加。' },

  { id: 'P_P10', module: 'python', type: 'coding', difficulty: 2, source: 'LeetCode Easy',
    question: '判断两个字符串是否为字母异位词（anagram，如 "listen" 和 "silent"）。',
    tags: ['字符串', '字典'],
    answer: 'def is_anagram(s, t):\n    return sorted(s) == sorted(t)',
    analysis: '字母异位词排序后相等。或用 Counter(s) == Counter(t) 判断。' },

  { id: 'P_P11', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '求列表中的最大值和最小值（不用内置 max/min）。',
    tags: ['列表'],
    answer: 'def find_max_min(nums):\n    mx = mn = nums[0]\n    for x in nums[1:]:\n        if x > mx:\n            mx = x\n        if x < mn:\n            mn = x\n    return mx, mn',
    analysis: '初始化最大最小为第一个元素，遍历比较更新。' },

  { id: 'P_P12', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '实现二分查找，返回目标值在有序列表中的下标，不存在返回 -1。',
    tags: ['二分查找'],
    answer: 'def binary_search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1',
    analysis: '每次比较中间元素，缩小一半搜索范围，O(log n) 时间。要求列表有序。' },

  { id: 'P_P13', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '判断一个数是否为素数。',
    tags: ['数学'],
    answer: 'def is_prime(n):\n    if n < 2:\n        return False\n    i = 2\n    while i * i <= n:\n        if n % i == 0:\n            return False\n        i += 1\n    return True',
    analysis: '小于 2 不是素数，试除到 sqrt(n) 即可。' },

  { id: 'P_P14', module: 'python', type: 'coding', difficulty: 2, source: '牛客网',
    question: '将一个字符串中的单词顺序反转（如 "hello world" -> "world hello"）。',
    tags: ['字符串'],
    answer: 'def reverse_words(s):\n    return " ".join(s.split()[::-1])',
    analysis: 'split() 按空白分割成单词列表，反转后再用空格连接。' },

  { id: 'P_P15', module: 'python', type: 'coding', difficulty: 2, source: 'LeetCode Easy',
    question: '给定一个非负整数 n，返回斐波那契数列第 n 项（n 从 0 开始）。',
    tags: ['动态规划', '递归'],
    answer: 'def fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a',
    analysis: '迭代滚动：a、b 依次更新，循环 n 次后 a 即第 n 项，O(n) 时间、O(1) 空间。' }
];
