/* ===== C语言题库：100道选择题 + 20道编程题 ===== */
window.C_QUESTIONS = [
  // ---------- 选择题 ----------
  { id: 'C_001', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '以下哪个选项能正确声明一个指向 int 类型的指针？',
    options: ['A. int *p;', 'B. int p*;', 'C. *int p;', 'D. int& p;'],
    answer: 'A', tags: ['指针', '基础语法'],
    analysis: 'C语言中声明指针的标准语法是 type *name;，因此 int *p; 正确。B 语法错误；C 的 *int 不是合法类型；D 是 C++ 的引用语法，C 语言没有引用。' },

  { id: 'C_002', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'C语言中，以下哪个是合法的标识符？',
    options: ['A. 2var', 'B. _count', 'C. my-var', 'D. int'],
    answer: 'B', tags: ['基础语法'],
    analysis: '标识符只能由字母、数字、下划线组成，且不能以数字开头，不能与关键字同名。_count 合法；2var 以数字开头非法；my-var 含连字符非法；int 是关键字。' },

  { id: 'C_003', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '以下哪个是正确的 main 函数写法？',
    options: ['A. void main()', 'B. int main()', 'C. main int()', 'D. int main() { return 0; } 和 B 等价即可'],
    answer: 'B', tags: ['函数', '基础语法'],
    analysis: '标准 C 规定 main 的返回类型为 int。int main() 是标准写法；A 的 void main() 不符合标准；C 语法错误。' },

  { id: 'C_004', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '表达式 5 / 2 的结果是？',
    options: ['A. 2.5', 'B. 2', 'C. 3', 'D. 2.0'],
    answer: 'B', tags: ['运算符'],
    analysis: '两个 int 相除是整数除法，结果截断小数部分，5 / 2 = 2。要得到 2.5 需写 5.0 / 2 或 (double)5 / 2。' },

  { id: 'C_005', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '表达式 7 % 3 的值是？',
    options: ['A. 2', 'B. 1', 'C. 0', 'D. 3'],
    answer: 'B', tags: ['运算符'],
    analysis: '% 是取余运算符，7 ÷ 3 = 2 余 1，所以 7 % 3 = 1。' },

  { id: 'C_006', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '执行 int a = 5; a = a++ + ++a; 后，a 的值是多少？（未定义行为题目，常见考点）',
    options: ['A. 11', 'B. 12', 'C. 13', 'D. 未定义行为，结果不确定'],
    answer: 'D', tags: ['运算符', '未定义行为'],
    analysis: 'a++ 与 ++a 在同一表达式中修改同一个变量，属于未定义行为（UB），C 标准不规定求值顺序，结果因编译器而异。应避免此类写法。' },

  { id: 'C_007', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'C语言中，字符常量 \'A\' 在内存中实际存储的是？',
    options: ['A. 字符 A', 'B. A 的 ASCII 码 65', 'C. 字符串 "A"', 'D. 空值'],
    answer: 'B', tags: ['数据类型'],
    analysis: 'char 本质是整数类型，字符常量存储的是其 ASCII 码值，\'A\' 的 ASCII 码是 65。' },

  { id: 'C_008', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '以下哪个是转义字符 \'\\n\' 的含义？',
    options: ['A. 换行', 'B. 制表符', 'C. 回车', 'D. 反斜杠'],
    answer: 'A', tags: ['基础语法'],
    analysis: '\\n 表示换行（newline），\\t 是制表符，\\r 是回车，\\\\ 是反斜杠。' },

  { id: 'C_009', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'sizeof(char) 的值通常是？',
    options: ['A. 1 字节', 'B. 2 字节', 'C. 4 字节', 'D. 8 字节'],
    answer: 'A', tags: ['数据类型', 'sizeof'],
    analysis: 'C 标准规定 sizeof(char) 恒为 1，即 char 占 1 字节。其他类型大小依平台而定。' },

  { id: 'C_010', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '在 64 位系统上，sizeof(int*) 通常是？',
    options: ['A. 4 字节', 'B. 8 字节', 'C. 1 字节', 'D. 不确定'],
    answer: 'B', tags: ['指针', 'sizeof'],
    analysis: '64 位系统指针通常为 8 字节；32 位系统为 4 字节。指针大小与目标类型无关。' },

  { id: 'C_011', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个声明了一个常量指针（指针本身不可变）？',
    options: ['A. const int *p', 'B. int *const p', 'C. const int *const p', 'D. int const *p'],
    answer: 'B', tags: ['指针', 'const'],
    analysis: 'int *const p 中 const 修饰 p，指针本身不可变，指向的内容可变。const int *p / int const *p 是指向常量的指针（内容不可变）。C 是两者都不可变。' },

  { id: 'C_012', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a[5]; 中，a[5] 是否合法？',
    options: ['A. 合法，最后一个元素', 'B. 非法，数组越界', 'C. 合法，表示数组大小', 'D. 编译时报错'],
    answer: 'B', tags: ['数组'],
    analysis: 'int a[5] 的有效下标是 0~4，a[5] 越界访问，属于未定义行为（编译器通常不报错，但运行时危险）。' },

  { id: 'C_013', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '数组名 a 在表达式 int a[10]; 中代表什么？',
    options: ['A. 第一个元素的地址', 'B. 整个数组的值', 'C. 第一个元素的值', 'D. 数组长度'],
    answer: 'A', tags: ['数组', '指针'],
    analysis: '在大多数表达式中，数组名会退化为指向第一个元素的指针，即 &a[0]。' },

  { id: 'C_014', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a[3] = {1, 2}; 中，a[2] 的值是？',
    options: ['A. 未初始化，随机值', 'B. 0', 'C. 2', 'D. 编译错误'],
    answer: 'B', tags: ['数组'],
    analysis: '数组部分初始化时，未显式初始化的元素被自动初始化为 0。所以 a[2] = 0。' },

  { id: 'C_015', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '字符串 "hello" 在内存中占几个字节？',
    options: ['A. 5', 'B. 6', 'C. 4', 'D. 8'],
    answer: 'B', tags: ['字符串'],
    analysis: '字符串常量末尾会自动添加一个空字符 \'\\0\' 作为结束标志，所以 "hello" 占 6 字节（5 个字符 + 1 个 \'\\0\'）。' },

  { id: 'C_016', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'strlen("abc\\0def") 的返回值是？',
    options: ['A. 7', 'B. 3', 'C. 4', 'D. 6'],
    answer: 'B', tags: ['字符串'],
    analysis: 'strlen 遇到第一个 \'\\0\' 就停止计数，"abc\\0def" 中第一个 \'\\0\' 在 c 之后，所以长度为 3。' },

  { id: 'C_017', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个函数用于比较两个字符串？',
    options: ['A. strcpy', 'B. strcmp', 'C. strcat', 'D. strlen'],
    answer: 'B', tags: ['字符串'],
    analysis: 'strcmp 比较字符串；strcpy 复制；strcat 连接；strlen 求长度。strcmp 返回 0 表示相等。' },

  { id: 'C_018', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'char s[10]; 使用 strcpy(s, "hello"); 后，strlen(s) 是？',
    options: ['A. 10', 'B. 5', 'C. 6', 'D. 不确定'],
    answer: 'B', tags: ['字符串'],
    analysis: 'strcpy 复制 "hello"（含 \'\\0\'）到 s，strlen(s) 计算的是字符串实际长度 5，与数组大小 10 无关。' },

  { id: 'C_019', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'switch 语句中，case 后通常需要跟什么关键字来跳出？',
    options: ['A. continue', 'B. break', 'C. return', 'D. exit'],
    answer: 'B', tags: ['控制流'],
    analysis: 'break 用于跳出 switch（或循环）。没有 break 会发生“贯穿”（fall-through），继续执行下一个 case。' },

  { id: 'C_020', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'for( ; ; ) 这个循环会？',
    options: ['A. 不执行', 'B. 无限循环', 'C. 执行一次', 'D. 编译错误'],
    answer: 'B', tags: ['控制流'],
    analysis: 'for 的三个部分都可以省略，省略循环条件等价于条件恒真，因此 for(;;) 是无限循环，需用 break 跳出。' },

  { id: 'C_021', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int i = 0; while (i < 3) { i++; } 循环结束后 i 的值是？',
    options: ['A. 2', 'B. 3', 'C. 4', 'D. 0'],
    answer: 'B', tags: ['控制流'],
    analysis: 'i 从 0 开始，循环体执行 3 次（i=0,1,2 时），每次 i++。i=2 时进入循环 i 变 3，此时 i<3 为假退出。所以 i=3。' },

  { id: 'C_022', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'do-while 循环和 while 循环的区别是？',
    options: ['A. 没区别', 'B. do-while 至少执行一次循环体', 'C. while 至少执行一次', 'D. do-while 更快'],
    answer: 'B', tags: ['控制流'],
    analysis: 'do-while 先执行循环体再判断条件，因此至少执行一次；while 先判断条件，可能一次都不执行。' },

  { id: 'C_023', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'continue 语句的作用是？',
    options: ['A. 结束整个循环', 'B. 跳过本次循环剩余部分，进入下一次循环', 'C. 跳出 switch', 'D. 退出程序'],
    answer: 'B', tags: ['控制流'],
    analysis: 'continue 跳过本次循环的剩余语句，直接进入下一次循环判断；break 才是结束整个循环。' },

  { id: 'C_024', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下代码中，x 的值是？\nint x = 0;\nif (x) printf("A"); else printf("B");',
    options: ['A. 输出 A', 'B. 输出 B', 'C. 都不输出', 'D. 编译错误'],
    answer: 'B', tags: ['控制流'],
    analysis: 'x = 0 在条件判断中为假，所以执行 else 分支，输出 B。' },

  { id: 'C_025', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个运算符优先级最高？',
    options: ['A. +', 'B. *', 'C. =', 'D. ,'],
    answer: 'B', tags: ['运算符'],
    analysis: '乘除（*）优先级高于加减（+），赋值（=）和逗号（,）优先级更低。括号 () 优先级最高。' },

  { id: 'C_026', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 1 << 4 的值是？',
    options: ['A. 4', 'B. 8', 'C. 16', 'D. 32'],
    answer: 'C', tags: ['位运算'],
    analysis: '左移运算符 << 将二进制位左移，1 << 4 = 1×2^4 = 16。' },

  { id: 'C_027', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 5 & 3 的值是？（按位与）',
    options: ['A. 1', 'B. 7', 'C. 0', 'D. 3'],
    answer: 'A', tags: ['位运算'],
    analysis: '5 = 0101，3 = 0011，按位与得 0001 = 1。' },

  { id: 'C_028', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 5 | 3 的值是？（按位或）',
    options: ['A. 7', 'B. 1', 'C. 8', 'D. 3'],
    answer: 'A', tags: ['位运算'],
    analysis: '5 = 0101，3 = 0011，按位或得 0111 = 7。' },

  { id: 'C_029', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 5 ^ 3 的值是？（按位异或）',
    options: ['A. 6', 'B. 7', 'C. 1', 'D. 3'],
    answer: 'A', tags: ['位运算'],
    analysis: '5 = 0101，3 = 0011，异或（不同为1）得 0110 = 6。' },

  { id: 'C_030', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '~0 的值是？（按位取反，假设 8 位）',
    options: ['A. 0', 'B. -1', 'C. 255', 'D. 1'],
    answer: 'B', tags: ['位运算'],
    analysis: '~0 把所有位取反，在补码表示下结果为全 1，即 -1。' },

  { id: 'C_031', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '以下哪个是合法的逻辑与运算符？',
    options: ['A. &&', 'B. &', 'C. ||', 'D. |'],
    answer: 'A', tags: ['运算符'],
    analysis: '&& 是逻辑与（短路求值）；|| 是逻辑或；& 是按位与；| 是按位或。' },

  { id: 'C_032', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a = 5; int b = 0; 表达式 (b != 0 && a / b > 1) 的值是？',
    options: ['A. 真', 'B. 假', 'C. 除零错误', 'D. 编译错误'],
    answer: 'B', tags: ['运算符', '短路'],
    analysis: '&& 有短路求值：b != 0 为假，整个表达式立即为假，不会执行 a / b，因此不会除零。' },

  { id: 'C_033', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: '三元运算符 a ? b : c 中，a 为 0 时结果是？',
    options: ['A. b', 'B. c', 'C. 0', 'D. 未定义'],
    answer: 'B', tags: ['运算符'],
    analysis: '条件为真（非0）取 b，为假（0）取 c。所以 a=0 时结果为 c。' },

  { id: 'C_034', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int x = 10; 执行 x += 5; 后 x 的值是？',
    options: ['A. 5', 'B. 10', 'C. 15', 'D. 50'],
    answer: 'C', tags: ['运算符'],
    analysis: 'x += 5 等价于 x = x + 5，即 15。' },

  { id: 'C_035', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'C语言中，函数定义时省略返回类型默认是？',
    options: ['A. void', 'B. int', 'C. char', 'D. 编译错误'],
    answer: 'B', tags: ['函数'],
    analysis: '传统 C 中，函数省略返回类型默认是 int（C99 已废弃此写法，建议显式声明）。' },

  { id: 'C_036', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '函数参数传递中，C 语言默认的传参方式是？',
    options: ['A. 引用传递', 'B. 值传递', 'C. 地址传递', 'D. 指针传递'],
    answer: 'B', tags: ['函数'],
    analysis: 'C 语言只有值传递：函数得到的是实参的副本，函数内修改形参不影响实参。要修改实参需传指针。' },

  { id: 'C_037', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下函数声明中，哪个表示“不返回任何值”？',
    options: ['A. int f();', 'B. void f();', 'C. char f();', 'D. f();'],
    answer: 'B', tags: ['函数'],
    analysis: 'void 表示无返回值；int 返回整数；char 返回字符。' },

  { id: 'C_038', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '函数内用 static 修饰的局部变量，其特点是？',
    options: ['A. 每次调用重新初始化', 'B. 只初始化一次，值在函数调用间保持', 'C. 只能被本文件访问', 'D. 存在栈上'],
    answer: 'B', tags: ['函数', '存储类别'],
    analysis: 'static 局部变量存储在静态区，只初始化一次，函数退出后其值保留，下次调用继续使用上次的值。' },

  { id: 'C_039', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '递归函数必须包含什么？',
    options: ['A. 循环', 'B. 递归出口（终止条件）', 'C. 指针', 'D. 全局变量'],
    answer: 'B', tags: ['函数', '递归'],
    analysis: '递归函数必须有终止条件（递归出口），否则会无限递归导致栈溢出。' },

  { id: 'C_040', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a = 5; int *p = &a; 则 *p 的值是？',
    options: ['A. a 的地址', 'B. 5', 'C. p 的地址', 'D. 未定义'],
    answer: 'B', tags: ['指针'],
    analysis: 'p 指向 a，*p 是解引用，取 p 所指向的内容，即 a 的值 5。' },

  { id: 'C_041', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a = 5; int *p = &a; int **pp = &p; 则 **pp 的值是？',
    options: ['A. 5', 'B. &a', 'C. &p', 'D. 未定义'],
    answer: 'A', tags: ['指针'],
    analysis: 'pp 是指向指针的指针，**pp 经过两次解引用，最终得到 a 的值 5。' },

  { id: 'C_042', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a[5] = {1,2,3,4,5}; int *p = a; 则 *(p + 2) 的值是？',
    options: ['A. 1', 'B. 2', 'C. 3', 'D. 4'],
    answer: 'C', tags: ['指针', '数组'],
    analysis: 'p 指向 a[0]，p+2 指向 a[2]，*(p+2) = a[2] = 3。指针加法按元素大小偏移。' },

  { id: 'C_043', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a[5]; 中，a[2] 与下列哪个等价？',
    options: ['A. *(a+2)', 'B. *a+2', 'C. &a[2]', 'D. a+2'],
    answer: 'A', tags: ['指针', '数组'],
    analysis: '数组下标 a[2] 等价于 *(a+2)。*a+2 是 *a（a[0]）加 2；&a[2] 是地址；a+2 是地址。' },

  { id: 'C_044', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '野指针指的是？',
    options: ['A. 指向空地址的指针', 'B. 指向已释放或未知内存的指针', 'C. 指向数组的指针', 'D. 空指针 NULL'],
    answer: 'B', tags: ['指针'],
    analysis: '野指针指向不可用或已释放的内存，使用野指针会导致未定义行为。应初始化指针或及时置 NULL。' },

  { id: 'C_045', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个宏表示空指针？',
    options: ['A. NULL', 'B. EOF', 'C. TRUE', 'D. VOID'],
    answer: 'A', tags: ['指针'],
    analysis: 'NULL 表示空指针常量；EOF 是文件结束标志（通常为 -1）。' },

  { id: 'C_046', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int *p; 使用 malloc 分配 10 个 int 的空间，正确的是？',
    options: ['A. p = malloc(10 * sizeof(int));', 'B. p = malloc(10);', 'C. p = malloc(10 * sizeof(p));', 'D. p = (int*)malloc(10 * sizeof(int));'],
    answer: 'D', tags: ['内存管理'],
    analysis: 'malloc 返回 void*，C 中可隐式转换但建议显式强转为 int*，大小应为 10 * sizeof(int)。A 在 C++ 中必须强转。' },

  { id: 'C_047', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'malloc 分配的内存位于？',
    options: ['A. 栈', 'B. 堆', 'C. 静态区', 'D. 寄存器'],
    answer: 'B', tags: ['内存管理'],
    analysis: 'malloc/calloc/realloc 在堆上分配内存，需用 free 手动释放；局部变量在栈上；全局/静态变量在静态区。' },

  { id: 'C_048', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'free 一个未由 malloc 分配的指针会？',
    options: ['A. 安全，无影响', 'B. 未定义行为，可能崩溃', 'C. 自动释放内存', 'D. 返回错误码'],
    answer: 'B', tags: ['内存管理'],
    analysis: 'free 只能用于 malloc/calloc/realloc 返回的指针，释放其他指针是未定义行为。free(NULL) 是安全的。' },

  { id: 'C_049', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'calloc(n, size) 和 malloc(n * size) 的主要区别是？',
    options: ['A. calloc 会初始化为 0', 'B. malloc 更快', 'C. calloc 分配栈内存', 'D. 无区别'],
    answer: 'A', tags: ['内存管理'],
    analysis: 'calloc 分配 n 个 size 大小的元素并将内存清零，malloc 不初始化（内容随机）。' },

  { id: 'C_050', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '内存泄漏指的是？',
    options: ['A. 栈溢出', 'B. 分配的内存未释放且无法再访问', 'C. 数组越界', 'D. 野指针'],
    answer: 'B', tags: ['内存管理'],
    analysis: '动态分配的内存不再使用却未 free，且失去了指向它的指针，导致无法释放，称为内存泄漏。' },

  { id: 'C_051', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'struct 结构体默认成员的访问权限是？',
    options: ['A. private', 'B. protected', 'C. public', 'D. 无访问控制概念'],
    answer: 'D', tags: ['结构体'],
    analysis: 'C 语言的 struct 没有访问控制（public/private 是 C++ 概念），所有成员默认都可通过对象直接访问。' },

  { id: 'C_052', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'struct Point { int x; int y; }; struct Point p; 如何访问 x 成员？',
    options: ['A. p->x', 'B. p.x', 'C. *p.x', 'D. &p.x'],
    answer: 'B', tags: ['结构体'],
    analysis: '通过结构体变量访问成员用点运算符 p.x；通过结构体指针访问用箭头运算符 p->x。' },

  { id: 'C_053', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'struct Point *p; 如何访问其 x 成员？',
    options: ['A. p.x', 'B. p->x', 'C. *p.x', 'D. p[x]'],
    answer: 'B', tags: ['结构体'],
    analysis: '通过结构体指针访问成员用箭头运算符 ->，即 p->x，等价于 (*p).x。' },

  { id: 'C_054', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'typedef 的作用是？',
    options: ['A. 定义新变量', 'B. 为已有类型起别名', 'C. 定义新类型', 'D. 声明函数'],
    answer: 'B', tags: ['typedef'],
    analysis: 'typedef 为已有类型起别名，例如 typedef int MyInt; 之后 MyInt 等价于 int。' },

  { id: 'C_055', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'enum 枚举类型默认第一个枚举常量的值是？',
    options: ['A. 1', 'B. 0', 'C. -1', 'D. 随机'],
    answer: 'B', tags: ['枚举'],
    analysis: '枚举常量默认从 0 开始，依次递增 1。可显式赋值改变。' },

  { id: 'C_056', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'union 联合体所有成员的特点是？',
    options: ['A. 各自独立存储', 'B. 共享同一块内存', 'C. 只读', 'D. 只能在函数外定义'],
    answer: 'B', tags: ['联合体'],
    analysis: 'union 所有成员共享同一块内存，同一时刻只能存储一个成员的值，大小为最大成员的大小。' },

  { id: 'C_057', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下预处理指令中，用于包含头文件的是？',
    options: ['A. #define', 'B. #include', 'C. #ifdef', 'D. #pragma'],
    answer: 'B', tags: ['预处理'],
    analysis: '#include 包含头文件；#define 定义宏；#ifdef 条件编译；#pragma 平台相关指令。' },

  { id: 'C_058', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '宏 #define SQUARE(x) x*x 存在什么问题？',
    options: ['A. 无问题', 'B. 宏参数应加括号，否则展开可能出错', 'C. 不能定义带参宏', 'D. 语法错误'],
    answer: 'B', tags: ['预处理', '宏'],
    analysis: 'SQUARE(1+2) 展开为 1+2*1+2=5 而非 9。正确写法是 #define SQUARE(x) ((x)*(x))。' },

  { id: 'C_059', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '#include <stdio.h> 与 #include "stdio.h" 的区别是？',
    options: ['A. 没区别', 'B. <> 优先搜索系统头文件目录，"" 优先搜索当前目录', 'C. "" 只搜索系统目录', 'D. <> 只搜索当前目录'],
    answer: 'B', tags: ['预处理'],
    analysis: '尖括号 <> 在系统标准头文件目录中查找；双引号 "" 先在当前目录查找，找不到再到系统目录查找。' },

  { id: 'C_060', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '条件编译 #ifdef 的作用是？',
    options: ['A. 定义变量', 'B. 根据宏是否定义决定是否编译某段代码', 'C. 包含头文件', 'D. 定义函数'],
    answer: 'B', tags: ['预处理'],
    analysis: '#ifdef 检查某宏是否已定义，用于条件编译，常用于防止头文件重复包含和平台适配。' },

  { id: 'C_061', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '文件操作中，fopen 的返回值类型是？',
    options: ['A. int', 'B. FILE*', 'C. char*', 'D. void'],
    answer: 'B', tags: ['文件操作'],
    analysis: 'fopen 返回 FILE* 类型的文件指针，打开失败返回 NULL。' },

  { id: 'C_062', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'fopen 的 "r" 模式表示？',
    options: ['A. 只写', 'B. 只读', 'C. 追加', 'D. 读写'],
    answer: 'B', tags: ['文件操作'],
    analysis: '"r" 只读；"w" 只写（覆盖）；"a" 追加；"r+" 读写；"w+" 读写（覆盖）。' },

  { id: 'C_063', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '文件使用完毕后应该调用哪个函数关闭？',
    options: ['A. fclose', 'B. close', 'C. fflush', 'D. free'],
    answer: 'A', tags: ['文件操作'],
    analysis: 'fclose 关闭文件并释放 FILE 指针；close 是系统调用用于文件描述符；fflush 刷新缓冲区。' },

  { id: 'C_064', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '读取一个字符的库函数是？',
    options: ['A. getchar', 'B. putchar', 'C. printf', 'D. gets'],
    answer: 'A', tags: ['输入输出'],
    analysis: 'getchar 从标准输入读取一个字符；putchar 输出一个字符；gets 读取字符串（已废弃，不安全）。' },

  { id: 'C_065', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'printf("%d", 3.14) 会输出什么？',
    options: ['A. 3.14', 'B. 3', 'C. 未定义行为', 'D. 编译错误'],
    answer: 'C', tags: ['输入输出'],
    analysis: '格式说明符 %d 期望 int，但传入 double，类型不匹配属于未定义行为。应使用 %f 或 %lf 输出浮点数。' },

  { id: 'C_066', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'printf("%.2f", 3.14159) 的输出是？',
    options: ['A. 3.14', 'B. 3.14159', 'C. 3.15', 'D. 3.1'],
    answer: 'A', tags: ['输入输出'],
    analysis: '%.2f 表示保留两位小数，3.14159 四舍五入到两位为 3.14。' },

  { id: 'C_067', module: 'c_language', type: 'choice', difficulty: 1, source: '牛客网',
    question: 'scanf 中读取一个 int 的格式说明符是？',
    options: ['A. %d', 'B. %f', 'C. %s', 'D. %c'],
    answer: 'A', tags: ['输入输出'],
    analysis: '%d 读 int；%f 读 float；%lf 读 double；%s 读字符串；%c 读字符。' },

  { id: 'C_068', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个关键字用于定义常量？',
    options: ['A. const', 'B. static', 'C. extern', 'D. register'],
    answer: 'A', tags: ['基础语法', 'const'],
    analysis: 'const 定义只读常量；static 定义静态变量；extern 声明外部变量；register 建议存入寄存器。' },

  { id: 'C_069', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'extern 关键字的作用是？',
    options: ['A. 定义新变量', 'B. 声明变量在其他文件定义', 'C. 定义静态变量', 'D. 定义常量'],
    answer: 'B', tags: ['存储类别'],
    analysis: 'extern 声明一个在其他源文件中定义的全局变量或函数，用于跨文件共享。' },

  { id: 'C_070', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '全局变量（未初始化）默认的初始值是？',
    options: ['A. 随机值', 'B. 0', 'C. 1', 'D. NULL 且无法使用'],
    answer: 'B', tags: ['存储类别'],
    analysis: '全局变量和 static 变量存储在静态区，未显式初始化时默认初始化为 0。' },

  { id: 'C_071', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '函数指针的声明正确的是？',
    options: ['A. int *f();', 'B. int (*f)();', 'C. int *(*f)();', 'D. (int *)f();'],
    answer: 'B', tags: ['函数指针'],
    analysis: 'int (*f)() 声明 f 是指向返回 int 的函数的指针。int *f() 是返回 int* 的函数。' },

  { id: 'C_072', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'void *p; 这种指针被称为？',
    options: ['A. 野指针', 'B. 空指针', 'C. 无类型指针', 'D. 函数指针'],
    answer: 'C', tags: ['指针'],
    analysis: 'void* 是无类型（通用）指针，可指向任意类型，使用前需强制转换为具体类型。' },

  { id: 'C_073', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a = 0; int *p = NULL; p = &a; 后，p 是？',
    options: ['A. 空指针', 'B. 指向 a 的指针', 'C. 野指针', 'D. 未定义'],
    answer: 'B', tags: ['指针'],
    analysis: 'p 先置 NULL，再赋值为 &a，此时 p 指向变量 a，不是空指针。' },

  { id: 'C_074', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a[3][4]; 中，数组元素的总数是？',
    options: ['A. 7', 'B. 12', 'C. 3', 'D. 4'],
    answer: 'B', tags: ['数组'],
    analysis: '二维数组 3 行 4 列，共 3 × 4 = 12 个元素。' },

  { id: 'C_075', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a[3][4] = {0}; 的作用是？',
    options: ['A. 只把 a[0][0] 设为 0', 'B. 把所有元素初始化为 0', 'C. 编译错误', 'D. 未定义'],
    answer: 'B', tags: ['数组'],
    analysis: '{0} 初始化会把第一个元素显式设为 0，其余元素按规则自动初始化为 0，等价于全部清零。' },

  { id: 'C_076', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a[5] = {1,2,3,4,5}; int *p = &a[1]; p[2] 的值是？',
    options: ['A. 3', 'B. 4', 'C. 5', 'D. 2'],
    answer: 'B', tags: ['指针', '数组'],
    analysis: 'p 指向 a[1]，p[2] = *(p+2) = a[3] = 4。' },

  { id: 'C_077', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '字符串拷贝，下列哪个是安全的做法？',
    options: ['A. 用 strcpy 不管长度', 'B. 用 strncpy 并确保不越界', 'C. 用 gets', 'D. 用 strcat'],
    answer: 'B', tags: ['字符串'],
    analysis: 'strncpy 可限制拷贝长度，避免缓冲区溢出；gets 不安全已废弃；strcat 是连接不是拷贝。' },

  { id: 'C_078', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '字符串 "A" 与字符 \'A\' 的区别是？',
    options: ['A. 完全相同', 'B. "A" 含 \'\\0\' 结尾，\'A\' 是单个字符', 'C. \'A\' 含 \'\\0\'', 'D. 没区别'],
    answer: 'B', tags: ['字符串'],
    analysis: '"A" 是字符串常量，实际存储 \'A\' 和 \'\\0\' 两个字节；\'A\' 是单个字符常量，占 1 字节。' },

  { id: 'C_079', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'break 语句可以出现在以下哪个结构中？',
    options: ['A. 只有 switch', 'B. 循环和 switch 中', 'C. 只有 for', 'D. 函数外'],
    answer: 'B', tags: ['控制流'],
    analysis: 'break 用于跳出循环（for/while/do-while）或 switch 语句。' },

  { id: 'C_080', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a = 3; int b = a << 1; 则 b 的值是？',
    options: ['A. 6', 'B. 3', 'C. 5', 'D. 1'],
    answer: 'A', tags: ['位运算'],
    analysis: '左移 1 位等价于乘以 2，3 << 1 = 6。' },

  { id: 'C_081', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '表达式 !5 的值是？',
    options: ['A. 5', 'B. 1', 'C. 0', 'D. -5'],
    answer: 'C', tags: ['运算符'],
    analysis: '! 是逻辑非，5 为真（非0），!5 为假（0）。' },

  { id: 'C_082', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int x = 5, y = 5; x == y 的值是？',
    options: ['A. 0', 'B. 1', 'C. 5', 'D. true 字符串'],
    answer: 'B', tags: ['运算符'],
    analysis: '== 是关系运算符，比较相等返回 1（真），不等返回 0（假）。5==5 为真，返回 1。' },

  { id: 'C_083', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a = 1, b = 2; 表达式 a > b ? a : b 的值是？',
    options: ['A. 1', 'B. 2', 'C. 0', 'D. 3'],
    answer: 'B', tags: ['运算符'],
    analysis: '三元运算符，a > b 为假，取 b 的值 2。' },

  { id: 'C_084', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下代码输出什么？\nint i = 0;\nprintf("%d", i++);\nprintf("%d", i);',
    options: ['A. 0 0', 'B. 1 1', 'C. 0 1', 'D. 1 0'],
    answer: 'C', tags: ['运算符'],
    analysis: 'i++ 先使用 i 的旧值 0 再自增，所以第一个输出 0；之后 i 变为 1，第二个输出 1。' },

  { id: 'C_085', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下代码输出什么？\nint i = 0;\nprintf("%d", ++i);',
    options: ['A. 0', 'B. 1', 'C. 未定义', 'D. 2'],
    answer: 'B', tags: ['运算符'],
    analysis: '++i 先自增再使用，i 变为 1 后输出 1。' },

  { id: 'C_086', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'C 语言中，数组下标从几开始？',
    options: ['A. 0', 'B. 1', 'C. -1', 'D. 随意'],
    answer: 'A', tags: ['数组'],
    analysis: 'C 语言数组下标从 0 开始，int a[5] 的下标范围是 0~4。' },

  { id: 'C_087', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'sizeof(int) 在大多数现代 32/64 位平台上通常是？',
    options: ['A. 2 字节', 'B. 4 字节', 'C. 8 字节', 'D. 1 字节'],
    answer: 'B', tags: ['数据类型'],
    analysis: '大多数平台 int 为 4 字节（32 位）；short 通常 2 字节；long 在 64 位 Linux 为 8 字节，Windows 为 4 字节。' },

  { id: 'C_088', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下哪个类型用于存储较大的整数（64位）？',
    options: ['A. int', 'B. long long', 'C. short', 'D. char'],
    answer: 'B', tags: ['数据类型'],
    analysis: 'long long 至少 64 位，可存储较大整数；int 通常 32 位；short 16 位；char 8 位。' },

  { id: 'C_089', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '浮点类型 double 通常占几字节？',
    options: ['A. 4', 'B. 8', 'C. 2', 'D. 16'],
    answer: 'B', tags: ['数据类型'],
    analysis: 'double 通常为 8 字节（双精度），float 为 4 字节（单精度）。' },

  { id: 'C_090', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下哪个不是 C 语言的关键字？',
    options: ['A. switch', 'B. main', 'C. case', 'D. default'],
    answer: 'B', tags: ['基础语法'],
    analysis: 'main 是函数名，不是关键字（虽然约定俗成作为入口）。switch/case/default 是关键字。' },

  { id: 'C_091', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'C 语言源文件编译执行的正确顺序是？',
    options: ['A. 编译→链接→预处理', 'B. 预处理→编译→汇编→链接', 'C. 链接→编译→执行', 'D. 预处理→链接→编译'],
    answer: 'B', tags: ['编译过程'],
    analysis: '标准流程：预处理（展开宏/头文件）→ 编译（生成汇编）→ 汇编（生成目标文件）→ 链接（生成可执行文件）。' },

  { id: 'C_092', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '头文件中常见的 include 保护（防止重复包含）写法是？',
    options: ['A. #ifndef XXX / #define XXX / ... / #endif', 'B. #pragma once 只能这样', 'C. 无需保护', 'D. #ifdef 保护'],
    answer: 'A', tags: ['预处理'],
    analysis: '标准做法是 #ifndef 头文件宏 / #define / 内容 / #endif；#pragma once 是编译器扩展（多数编译器支持）。' },

  { id: 'C_093', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int a = 5; int *p = &a; (*p)++; 后 a 的值是？',
    options: ['A. 5', 'B. 6', 'C. 未定义', 'D. 4'],
    answer: 'B', tags: ['指针'],
    analysis: '(*p)++ 先解引用得到 a，再自增，等价于 a++，所以 a 变为 6。' },

  { id: 'C_094', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'char *str = "hello"; str[0] = \'H\'; 会怎样？',
    options: ['A. 正常修改', 'B. 未定义行为（修改字符串常量）', 'C. 编译错误', 'D. 输出 H'],
    answer: 'B', tags: ['字符串', '指针'],
    analysis: '字符串常量存储在只读区，通过指针修改其内容是未定义行为，通常会导致段错误。应使用字符数组 char str[] = "hello"。' },

  { id: 'C_095', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下哪个函数可以把字符串转为整数？',
    options: ['A. atoi', 'B. itoa', 'C. sprintf', 'D. printf'],
    answer: 'A', tags: ['字符串', '库函数'],
    analysis: 'atoi（ASCII to int）把字符串转整数；itoa 是整数转字符串（非标准）；sprintf 是格式化输出到字符串。' },

  { id: 'C_096', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'int a = 10; while(a > 0) { if (a == 5) break; a--; } 循环结束时 a 是？',
    options: ['A. 0', 'B. 5', 'C. 10', 'D. 1'],
    answer: 'B', tags: ['控制流'],
    analysis: 'a 从 10 递减，当 a 减到 5 时执行 break 跳出循环，此时 a = 5。' },

  { id: 'C_097', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: 'int x = 5; int y = x * 2 + 3; 则 y 是？',
    options: ['A. 13', 'B. 16', 'C. 10', 'D. 15'],
    answer: 'A', tags: ['运算符'],
    analysis: '按优先级先乘后加：x*2=10，10+3=13。' },

  { id: 'C_098', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: '以下哪个是正确的函数调用？\nint add(int a, int b) { return a + b; }',
    options: ['A. add(1, 2);', 'B. add 1, 2;', 'C. add(1 2);', 'D. int add(1, 2);'],
    answer: 'A', tags: ['函数'],
    analysis: '函数调用语法为 函数名(实参列表)，add(1, 2) 正确。调用时不能加返回类型 int。' },

  { id: 'C_099', module: 'c_language', type: 'choice', difficulty: 3, source: '牛客网',
    question: '以下代码的输出是？\nint a = 5;\nprintf("%d %d", a, a++);',
    options: ['A. 6 5', 'B. 5 5', 'C. 未定义行为', 'D. 5 6'],
    answer: 'C', tags: ['未定义行为', '输入输出'],
    analysis: '函数参数的求值顺序是未指定的，同一表达式中既读取又修改 a，属于未定义行为，结果依编译器而定。' },

  { id: 'C_100', module: 'c_language', type: 'choice', difficulty: 2, source: '牛客网',
    question: 'C 语言中，一个 int 变量能被存储的最小单位是？',
    options: ['A. 位(bit)', 'B. 字节(byte)', 'C. 字(word)', 'D. 半字节'],
    answer: 'B', tags: ['数据类型'],
    analysis: '内存寻址的最小单位是字节（byte，8 位），变量至少占 1 字节。位字段可操作到 bit 但底层仍按字节存储。' },

  // ---------- 编程题 ----------
  { id: 'C_P01', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '编写一个函数，交换两个整数的值（要求用指针实现）。',
    tags: ['指针', '函数'],
    answer: 'void swap(int *a, int *b) {\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\n\n// 调用：swap(&x, &y);',
    analysis: 'C 语言是值传递，要修改实参必须传指针。函数内通过解引用交换两个变量所指向的值。' },

  { id: 'C_P02', module: 'c_language', type: 'coding', difficulty: 1, source: '牛客网',
    question: '输入一个整数 n，求 1 到 n 的和（用循环实现）。',
    tags: ['循环', '基础'],
    answer: 'int sum_to_n(int n) {\n    int sum = 0;\n    for (int i = 1; i <= n; i++) sum += i;\n    return sum;\n}',
    analysis: '累加器 sum 从 0 开始，循环 1 到 n 累加。也可用公式 n*(n+1)/2 直接计算。' },

  { id: 'C_P03', module: 'c_language', type: 'coding', difficulty: 2, source: 'LeetCode Easy',
    question: '判断一个整数是否为素数（质数）。',
    tags: ['循环', '数学'],
    answer: 'int is_prime(int n) {\n    if (n < 2) return 0;\n    for (int i = 2; i * i <= n; i++)\n        if (n % i == 0) return 0;\n    return 1;\n}',
    analysis: '小于 2 的不是素数；只需试除到 sqrt(n) 即可（写成 i*i<=n 避免浮点），若能整除则不是素数。' },

  { id: 'C_P04', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '计算 n 的阶乘（n!），分别用循环和递归实现。',
    tags: ['递归', '循环'],
    answer: '// 循环\nint fact_loop(int n) {\n    int r = 1;\n    for (int i = 2; i <= n; i++) r *= i;\n    return r;\n}\n// 递归\nint fact_rec(int n) {\n    if (n <= 1) return 1;\n    return n * fact_rec(n - 1);\n}',
    analysis: '循环版从 1 累乘到 n；递归版以 n<=1 为出口，n! = n * (n-1)!。注意阶乘增长快，n 较大时会溢出 int。' },

  { id: 'C_P05', module: 'c_language', type: 'coding', difficulty: 2, source: 'LeetCode Easy',
    question: '反转一个字符串（原地反转，用双指针）。',
    tags: ['字符串', '双指针'],
    answer: 'void reverse(char *s) {\n    int l = 0, r = strlen(s) - 1;\n    while (l < r) {\n        char t = s[l]; s[l] = s[r]; s[r] = t;\n        l++; r--;\n    }\n}',
    analysis: '左右双指针从两端向中间靠拢，逐对交换字符，直到相遇。时间复杂度 O(n)。' },

  { id: 'C_P06', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '求一个整型数组中的最大值。',
    tags: ['数组'],
    answer: 'int max_of_array(int a[], int n) {\n    int m = a[0];\n    for (int i = 1; i < n; i++)\n        if (a[i] > m) m = a[i];\n    return m;\n}',
    analysis: '假设第一个元素为最大，遍历其余元素，遇到更大的就更新。注意 n 至少为 1。' },

  { id: 'C_P07', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '统计一个字符串中每个字符出现的次数（ASCII 字符）。',
    tags: ['数组', '字符串'],
    answer: 'void count_chars(const char *s) {\n    int cnt[256] = {0};\n    for (int i = 0; s[i]; i++) cnt[(unsigned char)s[i]]++;\n    // cnt[c] 即字符 c 的出现次数\n}',
    analysis: '用大小为 256 的数组做哈希表，以下标对应 ASCII 码，遍历字符串累加。注意字符作下标前转为 unsigned char。' },

  { id: 'C_P08', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '实现一个函数，判断字符串是否为回文（如 "abcba"）。',
    tags: ['字符串', '双指针'],
    answer: 'int is_palindrome(const char *s) {\n    int l = 0, r = strlen(s) - 1;\n    while (l < r) {\n        if (s[l] != s[r]) return 0;\n        l++; r--;\n    }\n    return 1;\n}',
    analysis: '双指针从两端比较对应字符，都相等则是回文；遇到不等立即返回 0。' },

  { id: 'C_P09', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '用指针遍历一个 int 数组并输出所有元素。',
    tags: ['指针', '数组'],
    answer: 'void print_arr(int *a, int n) {\n    for (int *p = a; p < a + n; p++)\n        printf("%d ", *p);\n}',
    analysis: '指针 p 从数组首地址开始，每次解引用输出当前元素，p++ 移动到下一个元素（按 int 大小偏移）。' },

  { id: 'C_P10', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '实现一个简单的结构体并对其成员赋值、打印。',
    tags: ['结构体'],
    answer: 'struct Student {\n    char name[20];\n    int age;\n};\nint main() {\n    struct Student s;\n    strcpy(s.name, "Tom");\n    s.age = 20;\n    printf("%s %d", s.name, s.age);\n    return 0;\n}',
    analysis: '定义结构体 Student，用 strcpy 给字符数组赋值（不能直接 =），整数成员直接赋值，用 . 访问成员。' },

  { id: 'C_P11', module: 'c_language', type: 'coding', difficulty: 3, source: 'LeetCode Easy',
    question: '输入一个整数 n，输出斐波那契数列的第 n 项（n 从 0 开始）。',
    tags: ['递归', '动态规划'],
    answer: 'int fib(int n) {\n    if (n < 2) return n;\n    int a = 0, b = 1;\n    for (int i = 2; i <= n; i++) {\n        int c = a + b;\n        a = b; b = c;\n    }\n    return b;\n}',
    analysis: '迭代法：用两个变量滚动保存前两项，循环累加得到第 n 项，避免递归的指数级复杂度。' },

  { id: 'C_P12', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '实现冒泡排序，对一个 int 数组从小到大排序。',
    tags: ['排序', '数组'],
    answer: 'void bubble_sort(int a[], int n) {\n    for (int i = 0; i < n - 1; i++)\n        for (int j = 0; j < n - 1 - i; j++)\n            if (a[j] > a[j + 1]) {\n                int t = a[j]; a[j] = a[j + 1]; a[j + 1] = t;\n            }\n}',
    analysis: '相邻元素两两比较，大的往后“冒泡”。外层 n-1 轮，内层每轮确定一个最大元素，故内层范围递减。' },

  { id: 'C_P13', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '用递归求一个数组所有元素的和。',
    tags: ['递归', '数组'],
    answer: 'int arr_sum(int a[], int n) {\n    if (n == 0) return 0;\n    return a[n - 1] + arr_sum(a, n - 1);\n}',
    analysis: '递归出口 n==0 返回 0；否则返回最后一个元素加前 n-1 个元素之和。' },

  { id: 'C_P14', module: 'c_language', type: 'coding', difficulty: 3, source: 'LeetCode Easy',
    question: '判断一个整数是否为回文数（如 121 是回文，-121 不是）。',
    tags: ['数学', '循环'],
    answer: 'int is_palindrome_num(int x) {\n    if (x < 0) return 0;\n    int orig = x, rev = 0;\n    while (x) {\n        rev = rev * 10 + x % 10;\n        x /= 10;\n    }\n    return orig == rev;\n}',
    analysis: '负数一定不是回文。反转数字后与原数比较。注意反转过程可能溢出（可用 long long 避免）。' },

  { id: 'C_P15', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '输出 1 到 100 之间所有能被 3 整除的数。',
    tags: ['循环'],
    answer: 'for (int i = 1; i <= 100; i++)\n    if (i % 3 == 0)\n        printf("%d ", i);',
    analysis: '用取余判断 i % 3 == 0，循环 1 到 100 输出满足条件的数。' },

  { id: 'C_P16', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '实现字符串拷贝函数 strcpy 的功能（手写 my_strcpy）。',
    tags: ['字符串', '指针'],
    answer: 'char *my_strcpy(char *dst, const char *src) {\n    char *p = dst;\n    while ((*dst++ = *src++) != \'\\0\');\n    return p;\n}',
    analysis: '逐字符复制，直到复制了 \'\\0\' 结束。返回目标字符串首地址以便链式调用。注意 dst 要有足够空间。' },

  { id: 'C_P17', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '求两个整数的最大公约数（辗转相除法）。',
    tags: ['数学', '循环'],
    answer: 'int gcd(int a, int b) {\n    while (b) {\n        int t = a % b;\n        a = b;\n        b = t;\n    }\n    return a;\n}',
    analysis: '欧几里得算法：gcd(a,b)=gcd(b,a%b)，不断取余直到余数为 0，此时 a 即最大公约数。' },

  { id: 'C_P18', module: 'c_language', type: 'coding', difficulty: 2, source: '牛客网',
    question: '将一个字符串中的大写字母转换为小写字母。',
    tags: ['字符串'],
    answer: 'void to_lower(char *s) {\n    for (int i = 0; s[i]; i++)\n        if (s[i] >= \'A\' && s[i] <= \'Z\')\n            s[i] += 32;\n}',
    analysis: '大写字母 ASCII 码比对应小写字母小 32，加 32 即可转换。也可用库函数 tolower()。' },

  { id: 'C_P19', module: 'c_language', type: 'coding', difficulty: 3, source: 'LeetCode Easy',
    question: '给定一个整数数组和一个目标值 target，返回数组中和为 target 的两个元素下标（两数之和）。',
    tags: ['数组', '哈希'],
    answer: '// 暴力 O(n^2)\nint* two_sum(int *a, int n, int target) {\n    for (int i = 0; i < n; i++)\n        for (int j = i + 1; j < n; j++)\n            if (a[i] + a[j] == target) {\n                int *r = malloc(2 * sizeof(int));\n                r[0] = i; r[1] = j;\n                return r;\n            }\n    return NULL;\n}',
    analysis: '双循环枚举所有数对，找到和为 target 的返回下标。更优解可用哈希表做到 O(n)。' },

  { id: 'C_P20', module: 'c_language', type: 'coding', difficulty: 3, source: '牛客网',
    question: '统计一个整数在二进制表示中 1 的个数（位运算）。',
    tags: ['位运算'],
    answer: 'int count_ones(unsigned int n) {\n    int cnt = 0;\n    while (n) {\n        n = n & (n - 1); // 消去最低位的 1\n        cnt++;\n    }\n    return cnt;\n}',
    analysis: 'n & (n-1) 会消去 n 二进制最低位的 1，循环直到 n 为 0，循环次数即 1 的个数。' }
];
