/* ===== 行测题库：50道言语理解 + 30道逻辑推理 ===== */
window.XC_QUESTIONS = [
  // ---------- 言语理解（50） ----------
  { id: 'X_001', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"他的演讲逻辑清晰、_______，赢得了全场热烈的掌声。"',
    options: ['A. 夸夸其谈', 'B. 言之有物', 'C. 天花乱坠', 'D. 泛泛而谈'],
    answer: 'B', tags: ['成语辨析'],
    analysis: '语境是褒义，形容内容充实。"言之有物"指讲话或文章内容具体充实，符合。"夸夸其谈""天花乱坠"是贬义，"泛泛而谈"指肤浅不深入。' },

  { id: 'X_002', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"不积跬步，无以至千里"强调的是什么道理？',
    options: ['A. 要抓住机遇', 'B. 重视积累，从量变到质变', 'C. 要有远大理想', 'D. 做事要果断'],
    answer: 'B', tags: ['片段理解'],
    analysis: '这句话出自《劝学》，意思是不积累一步半步，就无法到达千里之外，强调点滴积累的重要性。' },

  { id: 'X_003', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"这项改革涉及面广，需要_______推进，不能急于求成。"',
    options: ['A. 稳步', 'B. 疾速', 'C. 盲目', 'D. 随意'],
    answer: 'A', tags: ['实词辨析'],
    analysis: '与"不能急于求成"呼应，应选表示稳妥循序的"稳步"。"疾速""盲目""随意"都与语境不符。' },

  { id: 'X_004', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"亡羊补牢"这个成语比喻的是？',
    options: ['A. 犯了错不改正', 'B. 出了问题后及时补救，还不算晚', 'C. 做事认真', 'D. 未雨绸缪'],
    answer: 'B', tags: ['成语'],
    analysis: '"亡羊补牢"意为羊丢了再去修补羊圈，比喻受到损失之后设法补救，免得再受损失，还不算晚。' },

  { id: 'X_005', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列词语中，没有错别字的一组是？',
    options: ['A. 再接再厉', 'B. 迫不急待', 'C. 名符其实', 'D. 甘败下风'],
    answer: 'A', tags: ['字形'],
    analysis: '"再接再厉"正确。"迫不急待"应为"迫不及待"，"名符其实"应为"名副其实"，"甘败下风"应为"甘拜下风"。' },

  { id: 'X_006', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子中，没有语病的一句是？',
    options: ['A. 通过这次活动，使我受到了深刻的教育。', 'B. 我们要不断提高自己的学习效率和学习成绩。', 'C. 这本书的内容和插图都很精彩。', 'D. 由于他刻苦学习，因此成绩很好。'],
    answer: 'C', tags: ['病句'],
    analysis: 'A"通过……使……"主语残缺；B"提高……成绩"搭配不当；D"由于……因此……"关联词重复。C 正确。' },

  { id: 'X_007', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列成语使用恰当的一项是？',
    options: ['A. 他犯了错误，大家对他不以为然。', 'B. 这件艺术品巧夺天工，令人叹为观止。', 'C. 他说话总是首当其冲。', 'D. 这里商品琳琅满目，令人俯拾皆是。'],
    answer: 'B', tags: ['成语使用'],
    analysis: '"巧夺天工"形容技艺精巧绝伦，用在这里正确。"不以为然"指不认为是对的（不同意），"首当其冲"指最先受到冲击，"俯拾皆是"形容多而容易得到，均使用不当。' },

  { id: 'X_008', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '填入横线处最恰当的是：\n"科学研究需要_______的精神，不能人云亦云。"',
    options: ['A. 亦步亦趋', 'B. 独立思考', 'C. 随波逐流', 'D. 循规蹈矩'],
    answer: 'B', tags: ['选词填空'],
    analysis: '与"不能人云亦云"呼应，应选"独立思考"。"亦步亦趋""随波逐流"是贬义，"循规蹈矩"指拘泥旧规。' },

  { id: 'X_009', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子排序最恰当的是：\n① 因此，学习必须持之以恒\n② 知识的积累是一个长期的过程\n③ 不能指望一蹴而就\n④ 三天打鱼两天晒网是学不好的',
    options: ['A. ②③④①', 'B. ②①③④', 'C. ④③②①', 'D. ①④③②'],
    answer: 'A', tags: ['语句排序'],
    analysis: '②先提出观点"知识积累是长期过程"，③"不能一蹴而就"承接，④"三天打鱼"作反面例证，①"因此"总结。顺序为②③④①。' },

  { id: 'X_010', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"他山之石，可以攻玉"的意思是？',
    options: ['A. 别的山上的石头可以打碎玉', 'B. 借助外力帮助自己提高', 'C. 玉石很坚硬', 'D. 要珍惜石头'],
    answer: 'B', tags: ['名句理解'],
    analysis: '比喻别国的贤才可为本国效力，或借助别人的长处来弥补自己的不足，帮助自己进步。' },

  { id: 'X_011', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"这座古城保存完好，走在其中仿佛_______了千年时光。"',
    options: ['A. 穿越', 'B. 超越', 'C. 穿过', 'D. 越过'],
    answer: 'A', tags: ['实词辨析'],
    analysis: '"穿越"指跨过时空，"穿越了千年时光"搭配恰当。"超越"指超过，"穿过""越过"多指空间上的通过。' },

  { id: 'X_012', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列各组词语中，加点字的读音完全相同的是？',
    options: ['A. 相形见绌（zhuō）', 'B. 呱呱坠地（guā）', 'C. 莘莘学子（shēn）', 'D. 乳臭未干（chòu）'],
    answer: 'C', tags: ['字音'],
    analysis: '"莘莘学子"读 shēn 正确。"相形见绌"读 chù；"呱呱坠地"读 gū；"乳臭未干"读 xiù。' },

  { id: 'X_013', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话主要想表达什么？\n"很多人认为努力就一定会有回报，但事实上，努力只是成功的必要条件，而非充分条件。方向、方法、机遇同样重要。"',
    options: ['A. 努力没有用', 'B. 成功需要努力，但仅有努力是不够的', 'C. 机遇决定一切', 'D. 不要努力'],
    answer: 'B', tags: ['主旨概括'],
    analysis: '文段强调努力是必要条件而非充分条件，还需方向、方法、机遇，即"努力必要但不充分"，选 B。' },

  { id: 'X_014', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"一诺千金"形容的是？',
    options: ['A. 说话算数，很有信用', 'B. 金钱很多', 'C. 承诺很多', 'D. 吝啬'],
    answer: 'A', tags: ['成语'],
    analysis: '"一诺千金"形容说话算数，极讲信用。出自《史记·季布栾布列传》。' },

  { id: 'X_015', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子没有语病的是？',
    options: ['A. 能否刻苦学习，是取得好成绩的关键。', 'B. 我们要养成认真读书的好习惯。', 'C. 他的写作水平明显改进了。', 'D. 防止校园欺凌事件不再发生。'],
    answer: 'B', tags: ['病句'],
    analysis: 'A"能否"与"是……关键"两面对一面；C"水平……改进"搭配不当（应为"提高"）；D"防止……不再"否定不当。B 正确。' },

  { id: 'X_016', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列成语中，与"未雨绸缪"意思最接近的是？',
    options: ['A. 亡羊补牢', 'B. 防患于未然', 'C. 临渴掘井', 'D. 事后诸葛'],
    answer: 'B', tags: ['成语辨析'],
    analysis: '"未雨绸缪"指趁天没下雨先修缮门窗，比喻事先做准备。"防患于未然"意思相同。A 是事后补救，C、D 都指事到临头才行动。' },

  { id: 'X_017', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"面对复杂局面，领导者必须保持清醒头脑，_______全局，_______重点。"',
    options: ['A. 统筹 突出', 'B. 抓住 忽略', 'C. 放弃 关注', 'D. 分散 强调'],
    answer: 'A', tags: ['选词填空'],
    analysis: '"统筹全局、突出重点"是常见搭配，符合领导者工作方法。"抓住……忽略""放弃……关注"逻辑不通。' },

  { id: 'X_018', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"因地制宜"的意思是？',
    options: ['A. 根据各地具体情况制定适宜的办法', 'B. 根据个人喜好做事', 'C. 固定不变的方法', 'D. 因地制宜只能用于农业'],
    answer: 'A', tags: ['成语'],
    analysis: '"因地制宜"指根据不同地区的具体情况，制定相应的适宜措施。' },

  { id: 'X_019', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列词语中，书写完全正确的一组是？',
    options: ['A. 一如既往', 'B. 走头无路', 'C. 义气用事', 'D. 变本加利'],
    answer: 'A', tags: ['字形'],
    analysis: '"一如既往"正确。"走头无路"应为"走投无路"，"义气用事"应为"意气用事"，"变本加利"应为"变本加厉"。' },

  { id: 'X_020', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话意在说明什么？\n"读书不仅要读，更要思考。光读不想，书还是书，你还是你，两者之间没有发生任何化学反应。"',
    options: ['A. 读书没有用', 'B. 读书要结合思考', 'C. 不要读书', 'D. 书很难读'],
    answer: 'B', tags: ['意图判断'],
    analysis: '文段强调"不仅要读，更要思考"，说明读书要结合思考才有收获，选 B。' },

  { id: 'X_021', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"集腋成裘"比喻的是？',
    options: ['A. 积少成多', 'B. 一举成功', 'C. 白费力气', 'D. 半途而废'],
    answer: 'A', tags: ['成语'],
    analysis: '"集腋成裘"指狐狸腋下的皮毛虽小，聚集起来却能制成裘衣，比喻积少成多。' },

  { id: 'X_022', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子中，标点符号使用正确的一项是？',
    options: ['A. 我不知道他去哪儿了？', 'B. 他问："你去吗？"', 'C. 今天下雨了、我们没去。', 'D. 我喜欢吃：苹果，香蕉。'],
    answer: 'B', tags: ['标点'],
    analysis: 'B 正确。A 是陈述句不该用问号（应为句号）；C"了、我们"顿号误用；D 冒号用法不当。' },

  { id: 'X_023', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"这座城市有着深厚的历史_______和独特的文化_______。"',
    options: ['A. 底蕴 氛围', 'B. 底细 气氛', 'C. 底色 气候', 'D. 底层 环境'],
    answer: 'A', tags: ['选词填空'],
    analysis: '"历史底蕴""文化氛围"是固定搭配。"底细"指内情，"底色""底层"均不合适。' },

  { id: 'X_024', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"纸上谈兵"的典故与下列哪位历史人物有关？',
    options: ['A. 赵括', 'B. 诸葛亮', 'C. 孙武', 'D. 韩信'],
    answer: 'A', tags: ['成语典故'],
    analysis: '"纸上谈兵"指战国时赵括只会空谈兵法理论，实战却大败于长平之战，比喻空谈理论不能解决实际问题。' },

  { id: 'X_025', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子没有语病的是？',
    options: ['A. 学校开展了一系列丰富多彩的活动。', 'B. 我们讨论并且听取了校长的报告。', 'C. 大约有五十人左右参加了会议。', 'D. 他的家乡是江苏南京人。'],
    answer: 'A', tags: ['病句'],
    analysis: 'A 正确。B 语序不当（应先听取后讨论）；C"大约"与"左右"重复；D"家乡是……人"主宾搭配不当。' },

  { id: 'X_026', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列成语中，含贬义的是？',
    options: ['A. 精益求精', 'B. 好高骛远', 'C. 脚踏实地', 'D. 一丝不苟'],
    answer: 'B', tags: ['成语感情色彩'],
    analysis: '"好高骛远"指不切实际地追求过高目标，含贬义。其余三个都是褒义。' },

  { id: 'X_027', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话的中心意思是？\n"手机方便了我们的生活，但过度依赖手机也会带来一系列问题，如视力下降、社交能力退化等。我们应合理使用手机。"',
    options: ['A. 手机一无是处', 'B. 要合理使用手机', 'C. 手机只带来问题', 'D. 应该扔掉手机'],
    answer: 'B', tags: ['主旨概括'],
    analysis: '文段先讲手机利弊，最后提出"应合理使用手机"，这是中心观点，选 B。' },

  { id: 'X_028', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"弄巧成拙"的意思是？',
    options: ['A. 本想取巧，反而坏了事', 'B. 巧妙成功了', 'C. 做事很顺利', 'D. 很有技巧'],
    answer: 'A', tags: ['成语'],
    analysis: '"弄巧成拙"指本想耍小聪明取巧，结果反而把事情办糟了。' },

  { id: 'X_029', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列各句中，成语使用不恰当的是？',
    options: ['A. 这篇文章文不加点，一气呵成。', 'B. 他对工作精益求精，一丝不苟。', 'C. 大家众说纷纭，莫衷一是。', 'D. 他见义勇为的事迹令人敬佩。'],
    answer: 'A', tags: ['成语使用'],
    analysis: '"文不加点"指文章一气呵成、无需修改，常被误用为"不加标点"。这里"文不加点，一气呵成"搭配有误（文不加点已含一气呵成之意，语义重复且易误解）。B、C、D 均正确。' },

  { id: 'X_030', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"我们要坚决_______不良风气，_______文明新风。"',
    options: ['A. 抵制 倡导', 'B. 支持 反对', 'C. 鼓励 抵制', 'D. 提倡 杜绝'],
    answer: 'A', tags: ['选词填空'],
    analysis: '对"不良风气"应"抵制"，对"文明新风"应"倡导"，语义搭配恰当。' },

  { id: 'X_031', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"望梅止渴"的故事与下列哪位人物有关？',
    options: ['A. 曹操', 'B. 刘备', 'C. 关羽', 'D. 孙权'],
    answer: 'A', tags: ['成语典故'],
    analysis: '曹操行军途中骗士兵前方有梅林，士兵口生津液暂解口渴，后比喻用空想安慰自己。' },

  { id: 'X_032', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子排序最恰当的是：\n① 从而提高了学习效率\n② 掌握了科学的学习方法\n③ 他认识到自己的不足\n④ 学习成绩也有了明显进步',
    options: ['A. ③②①④', 'B. ②①③④', 'C. ④③②①', 'D. ①④②③'],
    answer: 'A', tags: ['语句排序'],
    analysis: '③"认识到不足"是起因，②"掌握了方法"承接，①"从而提高效率"表结果，④"成绩进步"进一步结果。顺序③②①④。' },

  { id: 'X_033', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列词语中，"差"的读音与其他三项不同的是？',
    options: ['A. 差错', 'B. 出差', 'C. 参差', 'D. 差别'],
    answer: 'C', tags: ['字音'],
    analysis: '"参差"读 cēn cī，"差"读 cēn；其余读 chā。' },

  { id: 'X_034', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话主要说明了什么？\n"睡眠不足不仅影响第二天的精神状态，长期来看还会损害记忆力、降低免疫力，甚至增加患病风险。"',
    options: ['A. 睡眠不足的危害', 'B. 如何改善睡眠', 'C. 睡眠时间越长越好', 'D. 不用睡觉'],
    answer: 'A', tags: ['主旨概括'],
    analysis: '文段列举睡眠不足的种种危害，主旨是"睡眠不足的危害"，选 A。' },

  { id: 'X_035', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"画蛇添足"比喻的是？',
    options: ['A. 做事多此一举，反而坏事', 'B. 做事认真细致', 'C. 画画很厉害', 'D. 事半功倍'],
    answer: 'A', tags: ['成语'],
    analysis: '"画蛇添足"比喻做了多余的事，非但无益反而有害。' },

  { id: 'X_036', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子没有语病的是？',
    options: ['A. 我们要发扬和继承革命传统。', 'B. 这本书对我很感兴趣。', 'C. 他做了大量的工作，取得了显著的成绩。', 'D. 由于天气原因，因此运动会延期了。'],
    answer: 'C', tags: ['病句'],
    analysis: 'C 正确。A 语序不当（先继承后发扬）；B 主客颠倒（应"我对这本书很感兴趣"）；D"由于……因此"重复。' },

  { id: 'X_037', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"新产品的性能较旧款有了显著_______，受到了消费者的_______好评。"',
    options: ['A. 提升 一致', 'B. 降低 一致', 'C. 提升 分歧', 'D. 下降 广泛'],
    answer: 'A', tags: ['选词填空'],
    analysis: '性能应是"提升"，受好评应是"一致好评"，选 A。' },

  { id: 'X_038', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"画龙点睛"比喻的是？',
    options: ['A. 在关键处用精辟语言点明实质', 'B. 画画技术高超', 'C. 做事虎头蛇尾', 'D. 多余的一笔'],
    answer: 'A', tags: ['成语'],
    analysis: '"画龙点睛"指在关键处加上精妙的一笔，使内容更加生动传神，比喻说话做事抓住关键、点明实质。' },

  { id: 'X_039', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列词语中，与"专心致志"意思最接近的是？',
    options: ['A. 心不在焉', 'B. 全神贯注', 'C. 三心二意', 'D. 心猿意马'],
    answer: 'B', tags: ['近义词'],
    analysis: '"专心致志"和"全神贯注"都形容注意力高度集中。其余三个都表示不专心。' },

  { id: 'X_040', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话意在告诉我们什么？\n"遇到困难时，不要急着抱怨，静下心来分析原因、寻找办法，往往比焦虑更有用。"',
    options: ['A. 抱怨能解决问题', 'B. 遇到困难要冷静分析、积极解决', 'C. 焦虑是正常的', 'D. 困难无法解决'],
    answer: 'B', tags: ['意图判断'],
    analysis: '文段劝导人们遇困难要冷静分析、寻找办法，选 B。' },

  { id: 'X_041', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列成语中，不是形容勤奋学习的是？',
    options: ['A. 悬梁刺股', 'B. 凿壁偷光', 'C. 囊萤映雪', 'D. 守株待兔'],
    answer: 'D', tags: ['成语'],
    analysis: '"悬梁刺股""凿壁偷光""囊萤映雪"都形容刻苦读书。"守株待兔"比喻不劳而获、墨守成规。' },

  { id: 'X_042', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"互联网的普及极大地_______了人们获取信息的方式。"',
    options: ['A. 改变', 'B. 保持', 'C. 维持', 'D. 保留'],
    answer: 'A', tags: ['实词辨析'],
    analysis: '互联网"改变"了信息获取方式，符合语境。"保持""维持""保留"都表示不变。' },

  { id: 'X_043', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"滥竽充数"的故事讽刺的是？',
    options: ['A. 没有真才实学却混在行家里面充数', 'B. 音乐很好听', 'C. 乐器太多', 'D. 数量很多'],
    answer: 'A', tags: ['成语典故'],
    analysis: '南郭先生不会吹竽却混在乐队里，后比喻没有真才实学的人混在行家里充数。' },

  { id: 'X_044', module: 'xingce_yuyan', type: 'choice', difficulty: 3, source: '粉笔APP',
    question: '下列句子中，修辞手法判断正确的是？',
    options: ['A. "月亮像玉盘一样"是拟人', 'B. "小鸟在枝头唱歌"是比喻', 'C. "桃花潭水深千尺"是夸张', 'D. "青山处处埋忠骨"是设问'],
    answer: 'C', tags: ['修辞'],
    analysis: '"桃花潭水深千尺"运用夸张。A 是比喻（月亮像玉盘），B 是拟人（小鸟唱歌），D 不是设问。' },

  { id: 'X_045', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话的中心句是？\n"（1）阅读是获取知识的重要途径。（2）通过阅读，我们可以开阔视野。（3）阅读还能提升思维能力。（4）因此，我们要多读书、读好书。"',
    options: ['A. 第（1）句', 'B. 第（2）句', 'C. 第（3）句', 'D. 第（4）句'],
    answer: 'D', tags: ['中心句'],
    analysis: '前几句是分述阅读的好处，第（4）句"因此……"是总结、提出呼吁，是中心句。' },

  { id: 'X_046', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列词语中，意思与其他三项不同的是？',
    options: ['A. 井然有序', 'B. 有条不紊', 'C. 杂乱无章', 'D. 井井有条'],
    answer: 'C', tags: ['近反义词'],
    analysis: '"井然有序""有条不紊""井井有条"都形容整齐有序，"杂乱无章"形容杂乱无序，意思相反。' },

  { id: 'X_047', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '依次填入横线处最恰当的一组是：\n"生态环境一旦遭到破坏，要想_______往往需要付出巨大代价。"',
    options: ['A. 恢复', 'B. 破坏', 'C. 放弃', 'D. 回避'],
    answer: 'A', tags: ['实词辨析'],
    analysis: '生态被破坏后要"恢复"需付出代价，符合逻辑。其他三项与语境不符。' },

  { id: 'X_048', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '"程门立雪"的故事赞扬的是？',
    options: ['A. 尊师重道、虚心求教', 'B. 雪景很美', 'C. 不畏严寒', 'D. 勤奋工作'],
    answer: 'A', tags: ['成语典故'],
    analysis: '杨时拜见程颐，程颐正在打盹，杨时在雪中站立等候，后用来形容尊师重道、恭敬求教。' },

  { id: 'X_049', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '下列句子中，关联词使用正确的一项是？',
    options: ['A. 虽然天气很冷，但是我们坚持锻炼。', 'B. 因为他不来，所以会议照常进行。', 'C. 与其坐等，但是不如主动出击。', 'D. 不但他学习好，所以品德也好。'],
    answer: 'A', tags: ['关联词'],
    analysis: 'A"虽然……但是……"正确。B 因果不当（他不来与照常进行不是因果）；C"与其……不如……"搭配，不能用"但是"；D"不但……而且……"，不能用"所以"。' },

  { id: 'X_050', module: 'xingce_yuyan', type: 'choice', difficulty: 2, source: '粉笔APP',
    question: '这段话主要告诉我们什么？\n"真正的强者，不是没有眼泪的人，而是含着眼泪依然奔跑的人。"',
    options: ['A. 强者不会哭', 'B. 强者的定义是能克服困难、坚持前行', 'C. 哭泣是软弱', 'D. 奔跑就能变强'],
    answer: 'B', tags: ['意图判断'],
    analysis: '句子用对比强调"强者"是面对困难仍坚持前行的人，选 B。' },

  // ---------- 逻辑推理（30） ----------
  { id: 'X_101', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '苹果：水果，与下列哪组关系一致？',
    options: ['A. 老虎：动物', 'B. 汽车：轮子', 'C. 桌子：木头', 'D. 医生：医院'],
    answer: 'A', tags: ['类比推理'],
    analysis: '苹果是水果的一种，属于"包含关系（种属）"。老虎是动物的一种，关系一致。B、C 是组成关系，D 是场所关系。' },

  { id: 'X_102', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '如果"所有学生都要考试"为真，那么以下哪项必然为真？',
    options: ['A. 小明是学生，所以小明要考试', 'B. 小明要考试，所以小明是学生', 'C. 所有要考试的都是学生', 'D. 小明不是学生，所以不用考试'],
    answer: 'A', tags: ['翻译推理'],
    analysis: '题干是"学生→考试"。A 是肯前必肯后，正确。B 是肯后，推不出；C 是逆命题；D 否前推不出。' },

  { id: 'X_103', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '医生：病人，与下列哪组关系一致？',
    options: ['A. 教师：学生', 'B. 厨师：厨房', 'C. 作家：书籍', 'D. 演员：舞台'],
    answer: 'A', tags: ['类比推理'],
    analysis: '医生为病人服务，是"职业与对象"关系。教师为学生服务，关系一致。' },

  { id: 'X_104', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '一本书有 200 页，小明每天读 25 页，从周一开始读，第几天读完？',
    options: ['A. 第8天', 'B. 第7天', 'C. 第9天', 'D. 第6天'],
    answer: 'A', tags: ['数量关系'],
    analysis: '200 ÷ 25 = 8，正好第 8 天读完。' },

  { id: 'X_105', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '甲说："乙说谎。"乙说："丙说谎。"丙说："甲和乙都说谎。"如果三人中只有一人说真话，那么谁说的是真话？',
    options: ['A. 甲', 'B. 乙', 'C. 丙', 'D. 无法确定'],
    answer: 'B', tags: ['真假推理'],
    analysis: '假设甲真：则乙说谎，乙说"丙说谎"为假，即丙说真话，矛盾（只有一人真）。假设乙真：则丙说谎，即"甲乙都说谎"为假，甲说谎，成立。假设丙真：则甲乙都说谎，但甲说"乙说谎"为假意味着乙说真话，矛盾。故乙说真话。' },

  { id: 'X_106', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '钢笔：书写，与下列哪组关系一致？',
    options: ['A. 剪刀：裁剪', 'B. 桌子：木匠', 'C. 电脑：键盘', 'D. 学校：学生'],
    answer: 'A', tags: ['类比推理'],
    analysis: '钢笔的功能是书写，是"工具与功能"关系。剪刀的功能是裁剪，关系一致。' },

  { id: 'X_107', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '所有金属都能导电，铜是金属，所以铜能导电。这是哪种推理？',
    options: ['A. 演绎推理（三段论）', 'B. 归纳推理', 'C. 类比推理', 'D. 假设推理'],
    answer: 'A', tags: ['逻辑判断'],
    analysis: '从一般性前提（所有金属导电）推出个别结论（铜导电），是演绎推理中的三段论。' },

  { id: 'X_108', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '书籍：知识，与下列哪组关系一致？',
    options: ['A. 食物：营养', 'B. 书包：书本', 'C. 教室：桌椅', 'D. 汽车：轮胎'],
    answer: 'A', tags: ['类比推理'],
    analysis: '书籍是获取知识的载体（来源关系）。食物提供营养，关系一致。' },

  { id: 'X_109', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '如果明天不下雨，我们就去爬山。第二天没下雨，那么？',
    options: ['A. 一定去爬山了', 'B. 一定没去爬山', 'C. 可能去了也可能没去', 'D. 无法判断'],
    answer: 'A', tags: ['翻译推理'],
    analysis: '"不下雨→去爬山"，第二天"没下雨"是肯前，肯前必肯后，所以一定去了爬山。' },

  { id: 'X_110', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '3，6，12，24，？，数列中问号处应填？',
    options: ['A. 36', 'B. 48', 'C. 40', 'D. 30'],
    answer: 'B', tags: ['数字推理'],
    analysis: '后一项是前一项的 2 倍（等比数列），24 × 2 = 48。' },

  { id: 'X_111', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '甲、乙、丙三人年龄之和是 62 岁，甲比乙大 5 岁，乙比丙大 3 岁，则甲多少岁？',
    options: ['A. 24', 'B. 23', 'C. 22', 'D. 25'],
    answer: 'D', tags: ['数量关系'],
    analysis: '设丙 x 岁，则乙 x+3，甲 x+8，x+(x+3)+(x+8)=62，解得 3x+11=62，x=17。所以丙 17 岁，乙 20 岁，甲 25 岁。' },

  { id: 'X_112', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '夏天：炎热，与下列哪组关系一致？',
    options: ['A. 冬天：寒冷', 'B. 春天：落叶', 'C. 秋天：炎热', 'D. 春天：雪花'],
    answer: 'A', tags: ['类比推理'],
    analysis: '夏天具有炎热的特点（季节与特征）。冬天具有寒冷的特点，关系一致。' },

  { id: 'X_113', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '有的鸟不会飞，鸵鸟是鸟，所以？',
    options: ['A. 鸵鸟一定会飞', 'B. 鸵鸟一定不会飞', 'C. 鸵鸟可能不会飞', 'D. 无法判断'],
    answer: 'C', tags: ['逻辑判断'],
    analysis: '"有的鸟不会飞"只是部分，鸵鸟是鸟但不必然属于"不会飞"那一部分，故只能推出"可能不会飞"。' },

  { id: 'X_114', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '一个数列：1，1，2，3，5，8，？，问号处应填？',
    options: ['A. 11', 'B. 13', 'C. 12', 'D. 14'],
    answer: 'B', tags: ['数字推理'],
    analysis: '斐波那契数列：每项等于前两项之和，8+5=13。' },

  { id: 'X_115', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '下雨：地湿，与下列哪组关系一致？',
    options: ['A. 努力：成功（可能关系）', 'B. 生病：吃药', 'C. 开灯：黑暗', 'D. 喝水：口渴'],
    answer: 'A', tags: ['类比推理'],
    analysis: '下雨是地湿的原因之一（因果关系）。努力是成功的原因之一，关系最接近。' },

  { id: 'X_116', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '如果"甲→乙"为真，"非乙"为真，那么可以推出？',
    options: ['A. 甲', 'B. 非甲', 'C. 乙', 'D. 无法判断'],
    answer: 'B', tags: ['翻译推理'],
    analysis: '"甲→乙"等价于"非乙→非甲"（逆否命题）。已知非乙为真，所以非甲为真。' },

  { id: 'X_117', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '2，5，8，11，？，数列中问号处应填？',
    options: ['A. 13', 'B. 14', 'C. 15', 'D. 12'],
    answer: 'B', tags: ['数字推理'],
    analysis: '等差数列，公差 3，11+3=14。' },

  { id: 'X_118', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '医生：手术刀，与下列哪组关系一致？',
    options: ['A. 木匠：锯子', 'B. 教师：学校', 'C. 警察：小偷', 'D. 司机：马路'],
    answer: 'A', tags: ['类比推理'],
    analysis: '医生使用手术刀（职业与工具）。木匠使用锯子，关系一致。' },

  { id: 'X_119', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '某班学生，会游泳的比不会游泳的多 8 人，全班 40 人，问会游泳的有多少人？',
    options: ['A. 22', 'B. 24', 'C. 26', 'D. 20'],
    answer: 'B', tags: ['数量关系'],
    analysis: '设不会游泳 x 人，则会游泳 x+8，x+(x+8)=40，2x=32，x=16，会游泳=24。' },

  { id: 'X_120', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '成功：失败，与下列哪组关系一致？',
    options: ['A. 前进：后退', 'B. 努力：成功', 'C. 白天：太阳', 'D. 学习：知识'],
    answer: 'A', tags: ['类比推理'],
    analysis: '成功与失败是反义关系。前进与后退是反义关系，一致。' },

  { id: 'X_121', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '如果今天星期四，那么后天是星期几？',
    options: ['A. 星期六', 'B. 星期日', 'C. 星期五', 'D. 星期一'],
    answer: 'A', tags: ['逻辑判断'],
    analysis: '星期四的后一天是星期五，后天是星期六。' },

  { id: 'X_122', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '蜜蜂：蜂蜜，与下列哪组关系一致？',
    options: ['A. 奶牛：牛奶', 'B. 蝴蝶：花朵', 'C. 蜘蛛：网', 'D. 鸟：天空'],
    answer: 'A', tags: ['类比推理'],
    analysis: '蜜蜂产出蜂蜜（动物与产品）。奶牛产牛奶，关系一致。' },

  { id: 'X_123', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '1，4，9，16，？，数列中问号处应填？',
    options: ['A. 20', 'B. 24', 'C. 25', 'D. 36'],
    answer: 'C', tags: ['数字推理'],
    analysis: '依次为 1², 2², 3², 4²，下一项是 5²=25。' },

  { id: 'X_124', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '以下哪项最能削弱"多吃水果一定有益健康"这个结论？',
    options: ['A. 水果含维生素', 'B. 有些水果含糖量极高，过量食用有害', 'C. 医生建议吃水果', 'D. 水果种类很多'],
    answer: 'B', tags: ['削弱'],
    analysis: '题干结论是"一定有益"，B 指出某些水果过量食用有害，直接削弱"一定"的绝对性。' },

  { id: 'X_125', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '汽车：轮胎，与下列哪组关系一致？',
    options: ['A. 桌子：桌腿', 'B. 衣服：穿着', 'C. 房子：屋顶（部分）', 'D. 电脑：打字'],
    answer: 'A', tags: ['类比推理'],
    analysis: '轮胎是汽车的组成部分（组成关系）。桌腿是桌子的组成部分，关系一致。C 也是组成，但 A 更符合"整体与部分"的对应。' },

  { id: 'X_126', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '甲、乙、丙、丁四人中，只有一人会开车。甲说："我会开。"乙说："我不会开。"丙说："甲不会开。"丁说："我会开。"如果四人中只有一人说真话，谁会开车？',
    options: ['A. 甲', 'B. 乙', 'C. 丙', 'D. 丁'],
    answer: 'B', tags: ['真假推理'],
    analysis: '甲和丙的话矛盾，必有一真一假。因只有一人真，故乙、丁都说假话。乙说"我不会开"为假，说明乙会开车。验证：甲"我会开"假、丙"甲不会开"真，符合只有丙真。故乙会开车。' },

  { id: 'X_127', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '手：手指，与下列哪组关系一致？',
    options: ['A. 树：树枝', 'B. 书：文字', 'C. 花：香味', 'D. 房：门（部分）'],
    answer: 'A', tags: ['类比推理'],
    analysis: '手指是手的一部分（整体与部分）。树枝是树的一部分，关系一致。' },

  { id: 'X_128', module: 'xingce_logic', type: 'choice', difficulty: 3, source: '中公题库',
    question: '一根绳子对折两次后，从中间剪开，得到几段绳子？',
    options: ['A. 3', 'B. 4', 'C. 5', 'D. 2'],
    answer: 'C', tags: ['逻辑推理'],
    analysis: '对折两次后绳子有 4 股并在一起，从中间剪一刀，剪断 4 股，但由于对折处相连，最终得到 5 段。' },

  { id: 'X_129', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '以下哪项最能支持"坚持运动有助于改善情绪"这个结论？',
    options: ['A. 运动时会出汗', 'B. 研究表明运动能促进大脑分泌内啡肽，使人愉悦', 'C. 运动需要时间', 'D. 有人不喜欢运动'],
    answer: 'B', tags: ['加强'],
    analysis: 'B 从生理机制上解释运动改善情绪的原因，直接支持结论。' },

  { id: 'X_130', module: 'xingce_logic', type: 'choice', difficulty: 2, source: '中公题库',
    question: '2，4，8，16，32，？，问号处应填？',
    options: ['A. 48', 'B. 64', 'C. 60', 'D. 56'],
    answer: 'B', tags: ['数字推理'],
    analysis: '等比数列，公比 2，32×2=64。' }
];
